<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>哈尔滨华美太古开业启航报名</title>
<meta name="keywords" content="优居家博会" />
<meta name="description" content="优居家博会" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/heb/css/com.css?v1.1" />

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>

   <div class="swiper-container swiper-pages" id="swiper-container1">
        <div class="swiper-wrapper" id="wrapper">

			<div class="swiper-slide page-1 ps1">
			  <div class="container">
					<div class="am logo">
						<img src="/heb/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation an1" data-item="an1" data-delay="200" data-animation="bounceIn">
							<img src="/heb/images/p1-1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/heb/images/btn.png" class="click_btn"  data-id="1"/>
					</div>
				</div>
			  </div>

			<div class="swiper-slide page-2 ps2">
			  <div class="container">
					<div class="am logo">
						<img src="/heb/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation an1" data-item="an1" data-delay="200" data-animation="bounceIn">
							<img src="/heb/images/p2-1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/heb/images/btn.png" class="click_btn"  data-id="2"/>
						
					</div>
			  </div>
			</div>

			<div class="swiper-slide page-3 ps3">
			  <div class="container">
					<div class="am logo">
						<img src="/heb/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation an1" data-item="an1" data-delay="200" data-animation="bounceIn">
							<img data-src="/heb/images/p3-1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/heb/images/btn.png" class="click_btn"  data-id="3"/>
						
					</div>
			  </div>
			</div>

			<div class="swiper-slide page-4 ps4">
			  <div class="container">
					<div class="am logo">
						<img src="/heb/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation an1" data-item="an1" data-delay="200" data-animation="bounceIn">
							<img data-src="/heb/images/p4-1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/heb/images/btn.png" class="click_btn"  data-id="4"/>
						
					</div>
			  </div>
			</div>

			<div class="swiper-slide page-5 ps5">
			  <div class="container">
					<div class="am logo">
						<img src="/heb/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation an1" data-item="an1" data-delay="200" data-animation="bounceIn">
							<img data-src="/heb/images/p5-1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/heb/images/btn.png" class="click_btn"  data-id="5"/>
						
					</div>
			  </div>
			</div>
			
              
       </div>
    </div>
    <!-- 下滑提示 -->
  <!--   <div class="cn-slidetips next">
  	    <div class="slidetips">
  	        <a href="javascript:void(0);" title="NEXT" id="next">
  	            <img src="/heb/images/next.png" />
  	        </a>
  	    </div>
  	</div>   -->  
	

	<!-- 报名页 -->
	<div class="baoming hide" id="baoming">
		<div class="blackBg"></div>
		<div class="bmWarp">
			<!-- 领票 -->
			<div class="lpForm">
			    <p class="bmmsg">华美太古广场开业报名</p>
				<p><input type="text" name="name" class="name" placeholder="请填写姓名" /></p>
				<p><input type="number" name="tel" class="tel" placeholder="请填写手机号" /></p>
				<input type="hidden" id="btn_id" value=""/>
				<p class="lpBtn false">提交领票</p>	
			</div>
			
		</div>
	</div>

	<!-- 报名成功页 -->
	<div class="succeed hide" id="succeed">

		<div class="succeed-p">
			<img data-src="/heb/images/succeed.png" class="succeedImg" />
			<p>您已成功报名</p>
			<p>您的姓名、手机号</p>
			<p>作为接收入场唯一凭证</p>
		</div>
	
		
	</div>
	

	<!-- 通用提示 -->
	<div class="comTips hide" id="comTips">
		<div class="tipsWarp">
			<div class="tipsBody">
				提示
			</div>
			<div class="tipsClose">
				确认
			</div>
		</div>
	</div>

	<!-- loading 2.0 -->
	<div class="cn-spinner loading2 hide" id="loading2">
		<div class="spinner-warp">
	        <div class="spinner">
	            <div class="spinner-container container1">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container2">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container3">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	        </div>
	    </div>
    </div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script src="/common/js/tongji.js"></script>
<script src="/heb/js/my.js?v=1.1"></script>

<script src="/common/js/jweixin-1.0.0.js"></script>
<script>
	//微信分享控制
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
	   wx.onMenuShareAppMessage({
	      title: '哈尔滨华美太古开业启航报名',
	      desc: '哈尔滨华美太古开业启航报名',
	      link: '{{domain}}/phone/heb/index',
	      imgUrl: '{{domain}}/heb/images/p1-1.png',
	    });
	    wx.onMenuShareTimeline({
	        title: '哈尔滨华美太古开业启航报名',
	        link: '{{domain}}/phone/heb/index',
		    imgUrl: '{{domain}}/heb/images/p1-1.png',
	   });
	});
</script>

<div class="hmBox">
<script type="text/javascript"> var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://"); document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0ade9f144274d90bf98a25ed70333e57' type='text/javascript'%3E%3C/script%3E")) </script>
</div>
</body>
</html>