<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>比价11.11-奥普全国店庆活动</title>
<meta name="keywords" content="比价11.11-奥普全国店庆活动" />
<meta name="description" content="比价11.11-奥普全国店庆活动" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/shex/mobile/css/com.css?v=5.9" />

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>

   <div class="swiper-container swiper-pages" id="swiper-container1">
        <div class="swiper-wrapper" id="wrapper">

			<div class="swiper-slide page-1 ps1">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png"/>
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/shex/mobile/images/p1_1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="1"/>
					</div>
					<div class="am am3">主办方：优居网</div>
				</div>
			  </div>

			<div class="swiper-slide page-2 ps2">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/shex/mobile/images/p2_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/shex/mobile/images/p2_2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="2"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-3 ps3">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png"  />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p3_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/shex/mobile/images/p3_2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="3"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-4 ps4">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p4_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div id="swiper3" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
									<div class="swiper-slide">
										<ul class="pd">
											<li><img src="/shex/mobile/images/pd/1.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/2.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/3.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/4.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/5.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/6.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/7.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/8.jpg"  /></li>
										</ul>
										<p class="text">产品以秒杀页面为主</p>
									</div>
									<div class="swiper-slide">
										<ul class="pd">
											<li><img src="/shex/mobile/images/pd/9.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/10.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/11.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/12.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/13.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/14.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/15.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/16.jpg"  /></li>
										</ul>
										<p class="text">产品以秒杀页面为主</p>
									</div>
									<div class="swiper-slide">
										<ul class="pd">
											<li><img src="/shex/mobile/images/pd/17.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/18.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/19.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/20.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/21.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/22.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/23.jpg"  /></li>
											<li><img src="/shex/mobile/images/pd/24.jpg"  /></li>
										</ul>
										<p class="text">产品以秒杀页面为主</p>
									</div>
								</div>
							</div>

							<div class="pagination"></div>
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="4"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-5 ps5">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p5_1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="5"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-6 ps6">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p6_1.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="6"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-7 ps11">
				<div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p12-1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p12-2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="11"/>						
					</div>
					<div class="am am3">主办方：优居网</div>
				</div>
			</div>
			<div class="swiper-slide page-8 ps7">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p7_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/shex/mobile/images/p7_2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="7"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-9 ps8">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p8_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p8_2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="8"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-10 ps9">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png"  />
					</div>
					<div class="am am1">
						<img data-src="/shex/mobile/images/p9_1.png"  />
					</div>
					<div class="am am2">
							<div id="swiper2" class="swiper">
								<div class="swiper-container">
									<div class="swiper-wrapper">
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img src="/shex/mobile/images/logo/1.jpg"  />
												<img src="/shex/mobile/images/logo/2.jpg"  />
												<img src="/shex/mobile/images/logo/3.jpg"  />
												<img src="/shex/mobile/images/logo/4.jpg"  />
												<img src="/shex/mobile/images/logo/5.jpg"  />
												<img src="/shex/mobile/images/logo/6.jpg"  />
												<img src="/shex/mobile/images/logo/7.jpg"  />
												<img src="/shex/mobile/images/logo/8.jpg"  />
												<img src="/shex/mobile/images/logo/9.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/10.jpg"  />
												<img data-src="/shex/mobile/images/logo/11.jpg"  />
												<img data-src="/shex/mobile/images/logo/12.jpg"  />
												<img data-src="/shex/mobile/images/logo/13.jpg"  />
												<img data-src="/shex/mobile/images/logo/14.jpg"  />
												<img data-src="/shex/mobile/images/logo/15.jpg"  />
												<img data-src="/shex/mobile/images/logo/16.jpg"  />
												<img data-src="/shex/mobile/images/logo/17.jpg"  />
												<img data-src="/shex/mobile/images/logo/18.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/19.jpg"  />
												<img data-src="/shex/mobile/images/logo/20.jpg"  />
												<img data-src="/shex/mobile/images/logo/21.jpg"  />
												<img data-src="/shex/mobile/images/logo/22.jpg"  />
												<img data-src="/shex/mobile/images/logo/23.jpg"  />
												<img data-src="/shex/mobile/images/logo/24.jpg"  />
												<img data-src="/shex/mobile/images/logo/25.jpg"  />
												<img data-src="/shex/mobile/images/logo/26.jpg"  />
												<img data-src="/shex/mobile/images/logo/27.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/28.jpg"  />
												<img data-src="/shex/mobile/images/logo/29.jpg"  />
												<img data-src="/shex/mobile/images/logo/30.jpg"  />
												<img data-src="/shex/mobile/images/logo/31.jpg"  />
												<img data-src="/shex/mobile/images/logo/32.jpg"  />
												<img data-src="/shex/mobile/images/logo/33.jpg"  />
												<img data-src="/shex/mobile/images/logo/34.jpg"  />
												<img data-src="/shex/mobile/images/logo/35.jpg"  />
												<img data-src="/shex/mobile/images/logo/36.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/37.jpg"  />
												<img data-src="/shex/mobile/images/logo/38.jpg"  />
												<img data-src="/shex/mobile/images/logo/39.jpg"  />
												<img data-src="/shex/mobile/images/logo/40.jpg"  />
												<img data-src="/shex/mobile/images/logo/41.jpg"  />
												<img data-src="/shex/mobile/images/logo/42.jpg"  />
												<img data-src="/shex/mobile/images/logo/43.jpg"  />
												<img data-src="/shex/mobile/images/logo/44.jpg"  />
												<img data-src="/shex/mobile/images/logo/45.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/46.jpg"  />
												<img data-src="/shex/mobile/images/logo/47.jpg"  />
												<img data-src="/shex/mobile/images/logo/48.jpg"  />
												<img data-src="/shex/mobile/images/logo/49.jpg"  />
												<img data-src="/shex/mobile/images/logo/50.jpg"  />
												<img data-src="/shex/mobile/images/logo/51.jpg"  />
												<img data-src="/shex/mobile/images/logo/52.jpg"  />
												<img data-src="/shex/mobile/images/logo/53.jpg"  />
												<img data-src="/shex/mobile/images/logo/54.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/55.jpg"  />
												<img data-src="/shex/mobile/images/logo/56.jpg"  />
												<img data-src="/shex/mobile/images/logo/57.jpg"  />
												<img data-src="/shex/mobile/images/logo/58.jpg"  />
												<img data-src="/shex/mobile/images/logo/59.jpg"  />
												<img data-src="/shex/mobile/images/logo/60.jpg"  />
												<img data-src="/shex/mobile/images/logo/61.jpg"  />
												<img data-src="/shex/mobile/images/logo/62.jpg"  />
												<img data-src="/shex/mobile/images/logo/63.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/64.jpg"  />
												<img data-src="/shex/mobile/images/logo/65.jpg"  />
												<img data-src="/shex/mobile/images/logo/66.jpg"  />
												<img data-src="/shex/mobile/images/logo/67.jpg"  />
												<img data-src="/shex/mobile/images/logo/68.jpg"  />
												<img data-src="/shex/mobile/images/logo/69.jpg"  />
												<img data-src="/shex/mobile/images/logo/70.jpg"  />
												<img data-src="/shex/mobile/images/logo/71.jpg"  />
												<img data-src="/shex/mobile/images/logo/72.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/73.jpg"  />
												<img data-src="/shex/mobile/images/logo/74.jpg"  />
												<img data-src="/shex/mobile/images/logo/75.jpg"  />
												<img data-src="/shex/mobile/images/logo/76.jpg"  />
												<img data-src="/shex/mobile/images/logo/77.jpg"  />
												<img data-src="/shex/mobile/images/logo/78.jpg"  />
												<img data-src="/shex/mobile/images/logo/79.jpg"  />
												<img data-src="/shex/mobile/images/logo/80.jpg"  />
												<img data-src="/shex/mobile/images/logo/81.jpg"  />
											</div>
										</div>
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img data-src="/shex/mobile/images/logo/82.jpg"  />
												<img data-src="/shex/mobile/images/logo/83.jpg"  />
												<img data-src="/shex/mobile/images/logo/84.jpg"  />
												<img data-src="/shex/mobile/images/logo/85.jpg"  />
												<img data-src="/shex/mobile/images/logo/86.jpg"  />
											</div>
										</div>
									</div>
								</div>
								<div class="pagination"></div>
							</div>
						</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="9"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-11 ps10">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p10_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p10_2.png" />
						</div>
					</div>
					<div class="am am5">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p10_3.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="10"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-12 ps12">
			  <div class="container">
					<div class="am logo">
						<img src="/shex/mobile/images/logo.png" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p11_1.png" />
						</div>
					</div>
					<div class="am am4">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p11_3.png" />
						</div>
					</div>
					<div class="am am5">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/shex/mobile/images/p11_2.png" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/shex/mobile/images/btn1.png" class="click_btn"  data-id="12"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
              
       </div>
    </div>
    <!-- 下滑提示 -->
    <div class="cn-slidetips next">
  	    <div class="slidetips">
  	        <a href="javascript:void(0);" title="NEXT" id="next">
  	            <img src="/shex/mobile/images/next.png" />
  	        </a>
  	    </div>
  	</div>    
	

	<!-- 报名页 -->
	<div class="baoming hide" id="baoming">
		<div class="bmWarp">
			<div class="bmHead">
				<p class="lph">上海家博会0元领票</p>
				<p class="lpf hide">填写收票地址</p>
				<span class="bmClose">×</span>
			</div>
			<!-- 领票 -->
			<div class="lpForm">
			    <p class="bmmsg">已有<span class="bmnum">{{ count }}</span>人成功领到门票</p>
				<p><input type="text" name="name" class="name" placeholder="请填写姓名" /></p>
				<p><input type="number" name="tel" class="tel" placeholder="请填写手机号码" /></p>
				<p class="lpBtn false">提交领票</p>	
			</div>
			<!-- 提交验证 -->
			<div class="bmForm hide">
				<p>
					<select id="area" class="area">
						<option value="浦东新区">浦东新区</option>
					 	<option value="黄浦区">黄浦区</option>
						<option value="卢湾区">卢湾区</option>
						<option value="徐汇区">徐汇区</option>
						<option value="长宁区">长宁区</option>
					 	<option value="静安区">静安区</option>
						<option value="普陀区">普陀区</option>
						<option value="闸北区">闸北区</option>
						<option value="虹口区">虹口区</option>	
					 	<option value="杨浦区">杨浦区</option>
						<option value="闵行区">闵行区</option>
						<option value="宝山区">宝山区</option>
						<option value="嘉定区">嘉定区</option>
						<option value="金山区">金山区</option>
						<option value="松江区">松江区</option>
						<option value="青浦区">青浦区</option>
						<option value="奉贤区">奉贤区</option>
						<option value="崇明县">崇明县</option>
						<option value="其他区">其他区</option>	
					</select>
				</p>
				<p>
					<input type="text" id="address" name="address" class="address" placeholder="请填写详细地址" />
				</p>
				<p class="mtBig"><input type="number" name="code" class="code" placeholder="请输入验证码" /><span class="getCode">获取验证码</span>
				</p>
				<input type="hidden" id="send_phone" value=""/>
				<input type="hidden" id="btn_id" value=""/>
				<input type="hidden" id="verify" value=""/>
				<p class="tips"></p>				
				<p class="bmBtn false">提交验证</p>
			</div>
		</div>
	</div>

	<!-- 报名成功页 -->
	<div class="succeed hide" id="succeed">
		<div class="am logo">
			<img src="/shex/mobile/images/logo.png"/>
		</div>	
		<div class="succeed-p">
		<img data-src="/shex/mobile/images/succeed.png" class="succeedImg" />
		</div>
		<div class="succeedText1">
			<p>您已成功报名（上海）优居家博会</p>
			<p>您的姓名、手机、地址作为接收入场免费门票唯一凭证，工作人员会在72小时内跟您核对信息</p>
		</div>
		<div class="adBox">
			<img data-src="/shex/mobile/images/product/p1.png" data-url="http://wap.koudaitong.com/v2/goods/366ifqr1xdxrd" data-id="1" class="adImg"/>
			<img data-src="/shex/mobile/images/product/p2.png" data-url="http://wap.koudaitong.com/v2/goods/2ohpc1qtjo3yx" data-id="2" class="adImg" />
			<img data-src="/shex/mobile/images/product/p3.png?v=1.1" data-url="http://wap.koudaitong.com/v2/goods/1y3z1zx52cm7d" data-id="3" class="adImg" />
			<img data-src="/shex/mobile/images/product/p4.png" data-url="http://wap.koudaitong.com/v2/goods/366hx957z8pdl" data-id="4" class="adImg" />
			<img data-src="/shex/mobile/images/product/p5.png" data-url="http://wap.koudaitong.com/v2/goods/3extp8yun9ug9" data-id="5" class="adImg" />
			<img data-src="/shex/mobile/images/product/p6.png" data-url="http://wap.koudaitong.com/v2/goods/3nvb7dnzgiahl" data-id="6" class="adImg" />
			<img data-src="/shex/mobile/images/product/p7.png" data-url="http://wap.koudaitong.com/v2/goods/2xgfiuk8cr2ih" data-id="7" class="adImg" />
			<img data-src="/shex/mobile/images/product/p8.png" data-url="http://wap.koudaitong.com/v2/goods/3f0bffcjk2zop" data-id="8" class="adImg" />
			<img data-src="/shex/mobile/images/product/p9.png" data-url="http://wap.koudaitong.com/v2/goods/2ocr9j8f8d5mx" data-id="9" class="adImg" />
			<img data-src="/shex/mobile/images/product/p10.png?v=1.0" data-url="http://wap.koudaitong.com/v2/goods/26xr6gab8r76x" data-id="10" class="adImg" />
		</div>
		<!-- <div class="am am4">
			<a href="{{domain}}/phone/markdown/index/11"><img src="/shex/mobile/images/ad.gif" /></a>
		</div> -->
	</div>
	

	<!-- 通用提示 -->
	<div class="comTips hide" id="comTips">
		<div class="tipsWarp">
			<div class="tipsBody">
				提示
			</div>
			<div class="tipsClose">
				确认
			</div>
		</div>
	</div>

	<!-- loading 2.0 -->
	<div class="cn-spinner loading2 hide" id="loading2">
		<div class="spinner-warp">
	        <div class="spinner">
	            <div class="spinner-container container1">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container2">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container3">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	        </div>
	    </div>
    </div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>

<script src="/shex/mobile/js/my.js?v=5.9"></script>

<script src="/common/js/jweixin-1.0.0.js"></script>
<script>
	//微信分享控制
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
		var wxData = {
			"imgUrl":'{{domain}}/shex/mobile/images/share.jpg',
			"link":'{{domain}}/phone/shex/index',
			"desc":"限时免费-优居家博会门票限量发放！",
			"title":"限时免费-优居家博会门票限量发放！"
		};
		wx.onMenuShareAppMessage(wxData);
		wx.onMenuShareTimeline(wxData);
	});
</script>

<script src="/common/js/tongji.js"></script>
<div class="hmBox">
<script type="text/javascript"> var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://"); document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0ade9f144274d90bf98a25ed70333e57' type='text/javascript'%3E%3C/script%3E")) </script>
</div>
</body>
</html>