<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>七夕家装节</title>
<meta name="keywords" content="七夕家装节" />
<meta name="description" content="七夕家装节" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/qixi/css/com.css?v=4.7" />

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>

   <div class="swiper-container swiper-pages" id="swiper-container1">
        <div class="swiper-wrapper" id="wrapper">

              <div class="swiper-slide page-1 ps1">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am2">
							<div class="animation1 an2" data-item="an2" data-delay="400" data-animation1="bounceIn">
								<img src="/qixi/images/p1_2.png" />
								<p class="t1"><?php echo $content['address']?></p>
								<p class="t2" class="t1">{{ content['time'] }}</p>
								<p class="t3"><?php echo $content['city']?></p>
							</div>
						</div>
						<div class="am am1">
							<!-- <img src="/qixi/images/<?php echo $content['city_code']?>/p1_1.png?v=1.0" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/> -->
							<img src="/qixi/images/p1_3.png" />
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="1"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>
              </div>

              <div class="swiper-slide page-2 ps2">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img src="/qixi/images/p2_1.png?v=1.0" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
							<!-- <img src="/qixi/images/p2_2.png?v=1.0" class="animation1 an2" data-item="an2" data-delay="400" data-animation1="bounceIn"/> -->
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="2"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>

			  <div class="swiper-slide page-3 ps3">
				  <div class="container">
  						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p33_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
						</div>

						<div class="am am2">
							<div id="swiper3" class="swiper">
								<div class="swiper-container">
									<div class="swiper-wrapper">
										<div class="swiper-slide">
											<img src="/qixi/images/p33_2.png"  />
											<p class="text">产品以秒杀页面为主</p>
										</div>
										<div class="swiper-slide">
											<img src="/qixi/images/p33_3.png"  />
											<p class="text">产品以秒杀页面为主</p>
										</div>
									</div>
								</div>

								<div class="pagination"></div>
							</div>
						</div>
						
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="9"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
					    </div>
				  </div>                
			  </div>



			 <!--  <div class="swiper-slide page-4 ps4">
			 				  <div class="container">
			 						<div class="am logo1">
			 							<img src="/qixi/images/logo1.png"  />
			 						</div>
			 <div class="am logo2">
			 							<img src="/qixi/images/logo2.png"  />
			 						</div>
			 						<div class="am cityOpen">
			 							<span><?php echo $content['city']?>站</span>
			 						</div>
			 						<div class="am am1">
			 							<img data-src="/qixi/images/p3_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
			 <img src="/qixi/images/p3_2.png" class="animation1 an2 pab" data-item="an2" data-delay="200" data-animation1="bounceIn"/>
			 							<img src="/qixi/images/p3_3.png" class="animation1 an3 pab" data-item="an3" data-delay="200" data-animation1="bounceIn"/>
			 							<img src="/qixi/images/p3_4.png" class="animation1 an4 pab" data-item="an4" data-delay="400" data-animation1="fadeInUp"/>
			 							<img src="/qixi/images/p3_5.png" class="animation1 an5 pab" data-item="an5" data-delay="600" data-animation1="fadeInUp"/>
			 							<img src="/qixi/images/p3_6.png" class="animation1 an6 pab" data-item="an6" data-delay="800" data-animation1="fadeInUp"/>
			 							<img src="/qixi/images/p3_7.png" class="animation1 an7 pab" data-item="an7" data-delay="1000" data-animation1="fadeInUp"/>
			 
			 						</div>
			 						<div class="am bmOpen">
			 							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="3"/>
			 							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
			 						</div>
			 				  </div>                
			 </div> -->
			  
			  
			  <div class="swiper-slide page-4 ps4">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p4_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="fadeInUp"/>
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="4"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>
			  <div class="swiper-slide page-5 ps4_new">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p3_1_new.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
	 					</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="10"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>
			  <div class="swiper-slide page-6 ps6">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p5_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
						</div>
						<div class="am am2">
							<div id="swiper2" class="swiper">
								<div class="swiper-container">
									<div class="swiper-wrapper">
									{% for k,key in brand_arr %}
										<div class="swiper-slide">
											<div class="logoImgBox">
											    {% for k_vo,key_vo in key %}
												<img data-src="/qixi/images/logo/{{ key_vo }}.jpg"  />
												{% endfor %}
											</div>
											<p class="text">区域品牌</p>
										</div>
                                    {% endfor %}
									{% if content['city_code'] != 'taiyuan' %}
										<div class="swiper-slide">
											<div class="logoImgBox">
												<img src="/qixi/images/logo/13.jpg"  />
												<img src="/qixi/images/logo/41.jpg"  />
												<img src="/qixi/images/logo/42.jpg"  />
												<img src="/qixi/images/logo/6.jpg?v=1.0"  />
												<img src="/qixi/images/logo/23.jpg"  />
												<!-- <img src="/qixi/images/logo/30.jpg"  />
												<img src="/qixi/images/logo/65.jpg"  />
												<img src="/qixi/images/logo/76.jpg"  />
												<img src="/qixi/images/logo/25.jpg"  /> -->
											</div>
											<p class="text">战略品牌</p>
										</div>
									{% endif %}
									</div>
								</div>
								<div class="pagination"></div>
							</div>
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="5"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>
			  
			  <div class="swiper-slide page-7 ps7">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p6_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="fadeInUp"/>
							<img data-src="/qixi/images/p6_2.png" class="animation1 an2" data-item="an2" data-delay="400" data-animation1="fadeInUp"/>
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="6"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>
			  
			  <div class="swiper-slide page-8 ps8">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/p7_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
						</div>
						<div class="am am2">
							<img data-src="/qixi/images/p7_2.png" class="animation1 an2" data-item="an2" data-delay="400" data-animation1="fadeInUp"/>
						</div>
						<div class="am am3">
							<img data-src="/qixi/images/p7_3.png" class="animation1 an3" data-item="an3" data-delay="600" data-animation1="fadeInUp"/>
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="7"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>
			  </div>
			  
			  <div class="swiper-slide page-9 ps9">
				  <div class="container">
						<div class="am logo1">
							<img src="/qixi/images/logo1.png"  />
						</div>
<!-- 						<div class="am logo2">
							<img src="/qixi/images/logo2.png"  />
						</div> -->
						<div class="am cityOpen">
							<span><?php echo $content['city']?>站</span>
						</div>
						<div class="am am1">
							<img data-src="/qixi/images/<?php echo $content['city_code']?>/p8_1.png" class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn"/>
						</div>
						<div class="am am2">
							<p class="animation1 an2 " data-item="an2" data-delay="400" data-animation1="fadeInUp">活动日期</p>
							<p class="animation1 an3" data-item="an3" data-delay="600" data-animation1="fadeInUp">{{ content['time'] }}</p>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInUp">地址</p>
							<p class="animation1 an5" data-item="an5" data-delay="1000" data-animation1="fadeInUp"><?php echo $content['address']?></p>
						</div>
						<div class="am am3">
							<p  class="animation1 an1 " data-item="an1" data-delay="1200" data-animation1="fadeInUp">参与品牌，奖品及礼品以落地城市为准；本活动最终解释权归深圳市亚太传媒网络技术开发有限公司所有</p>
						</div>
						<div class="am bmOpen">
							<img src="/qixi/images/btn1.png" class="animation1 an3 click_btn" data-item="an3" data-delay="600" data-animation1="fadeInDown" data-id="8"/>
							<p class="animation1 an4" data-item="an4" data-delay="800" data-animation1="fadeInDown">主办方：腾讯网 · 亚太家居 我买家 优居网</p>
						</div>
				  </div>                
			  </div>
       </div>
		<div class="pagination" id="pagination1"></div>
    </div>
    <!-- 下滑提示 -->
    <div class="cn-slidetips next">
      	    <div class="slidetips">
      	        <a href="javascript:void(0);" title="NEXT" id="next">
      	            <img src="/qixi/images/next.png" />
      	        </a>
      	    </div>
      	</div>    
	<!-- 城市选择 -->
	<!-- <div class="citySelect bounceInDown animation1" id="citySelect"> -->
	<div class="citySelect hide" id="citySelect">
		<div class="black_bg"></div>
		<div class="cityWarp">
			<div class="cityHead">
				<img src="/qixi/images/logo3.png" class="logo-1" />
				<!-- <img src="/qixi/images/logo2.png" class="logo2" /> -->
				<p class="cityClose"><span><?php echo $content['city']?>站</span></p>
			</div>
			<div class="cityBody">
				<p class="ip">您目前所在的城市为：<span><?php echo $content['location_city']?></span></p>
				{% if is_city <> '' %}
				<p class="grey">您当前选择的城市站为：<span style="font-weight: bold;color:#e70000"><?php echo $content['city']?>站</span></p>
				{% else %}
				<p class="grey">我们为您推荐最近城市站：<span style="font-weight: bold;color:#e70000"><?php echo $content['city']?>站</span>，您也可以选择：</p>
				{% endif %}
				<div class="city cf">
					<a href="?city=hangzhou">杭州</a>
					<a href="?city=tianjin">天津</a>
					<a href="?city=wuhan">武汉</a>
					<a href="?city=nanjing">南京</a>
					<a href="?city=xiamen" class="mr0">厦门</a>
					<a href="?city=nanchang">南昌</a>
					<a href="?city=kunming">昆明</a>
					<a href="?city=xian">西安</a>
					
					<a href="?city=changsha">长沙</a>
					<a href="?city=jinan" class="mr0">济南</a>
					<a href="?city=haerbin">哈尔滨</a>
					<a href="?city=guiyang">贵阳</a>
					<a href="?city=taiyuan">太原</a>
					<a href="?city=qingdao">青岛</a>
					<a href="?city=beijing" class="mr0">北京</a>
					<a href="?city=zhengzhou">郑州</a>
					<a href="?city=dongguan">东莞</a>
				<!--<a href="?city=shijiazhuang">石家庄</a>
 					<a href="./?city=ningbo">宁波</a>
					<a href="./?city=shenzhen">深圳</a>
					<a href="./?city=guangzhou">广州</a>
					<a href="./?city=wuxi">无锡</a>
					<a href="./?city=shanghai">上海</a> -->
				</div>
			</div>
		</div>
	</div>

	<!-- 报名页 -->
	<div class="baoming hide" id="baoming">
		<div class="bmWarp">
			<div class="bmHead">
				<p class="lph">七夕家装节0元领票</p>
				<p class="lpf hide">验证领票信息</p>
				<span class="bmClose">×</span>
			</div>
			<!-- 领票 -->
			<div class="lpForm">
			    <p class="bmmsg">已有<span class="bmnum">{{ count }}</span>人成功领到门票</p>
				<p><input type="text" name="name" class="name" placeholder="请填写姓名" /></p>
				<p><input type="number" name="tel" class="tel" placeholder="请填写手机号码" /></p>
				<p class="lpBtn false">提交领票</p>	
			</div>
			<!-- 提交验证 -->
			<div class="bmForm hide">
				<p class="mtBig"><input type="number" name="code" class="code" placeholder="请输入验证码" /><span class="getCode">获取验证码</span></p>
				<input type="hidden" id="send_phone" value=""/>
				<input type="hidden" id="btn_id" value=""/>
				<input type="hidden" id="verify" value=""/>
				<p class="tips"></p>				
				<p class="bmBtn false">提交验证</p>
			</div>
		</div>
	</div>

	<!-- 报名成功页 -->
	<div class="succeed hide" id="succeed">
		<div class="am logo1">
			<img src="/qixi/images/logo1.png"  />
		</div>
<!-- 		<div class="am logo2">
			<img src="/qixi/images/logo2.png"  />
		</div> -->
		<div class="am cityOpen">
			<p><?php echo $content['city']?>站∨</p>
		</div>
		<div class="succeed-p">
		<img src="/qixi/images/succeed.png" class="succeedImg" />
		</div>
		<div class="succeedText1">
			<p>您已成功报名（<?php echo $content['city']?>）家装节</p>
			<p>您的姓名和手机号将作为您入场的唯一凭证</p>
		</div>
		<div class="succeedText2">
			<p>{{ content['time'] }}</p>
			<p>腾讯家居全国第二届七夕家装节</p>
			<p><?php echo $content['city']?>站·震撼来袭</p>
			<p>期待您的到来</p>
		</div>
	</div>
	
	<!-- 底部通栏 -->
	{% if is_weixin == 1 %}
    <div class="bottomNav" id="bottomNav">
		<a class="bn home" href="#"><span class="line"></span></a>
		<a class="bn bk" href="/phone/markdown/index/4">我的帮砍<span class="line"></span></a>
		<a class="bn ms" href="/phone/seckill/index/2">我的秒杀<span class="line"></span></a>
		<a class="bn hb" href="/phone/hongbao/list">我的抵购券</a>
	</div>
    {% endif %}
	<!-- 通用提示 -->
	<div class="comTips hide" id="comTips">
		<div class="tipsWarp">
			<div class="tipsBody">
				tips
			</div>
			<div class="tipsClose">
				确认
			</div>
		</div>
	</div>

	<!-- loading 2.0 -->
	<div class="cn-spinner loading2 hide" id="loading2">
		<div class="spinner-warp">
	        <div class="spinner">
	            <div class="spinner-container container1">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container2">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container3">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	        </div>
	    </div>
    </div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script src="/common/js/tongji.js"></script>
<script src="/qixi/js/my.js?v=4.7"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>

<script>
	//微信分享控制
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
		var wxData = {
			"imgUrl":'{{domain}}/qixi/images/share1.jpg?v=1.0',
			"link":'{{domain}}/phone/qixi/index',
			"desc":"限时免费-七夕家装节门票限量发放！",
			"title":"限时免费-七夕家装节门票限量发放！"
		};
		wx.onMenuShareAppMessage(wxData);
		wx.onMenuShareTimeline(wxData);
	});
</script>
</body>
</html>