<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<link href="/admin/css/summernote.css" rel="stylesheet">
<script src="/admin/js/summernote.min.js"></script>
<script src="/admin/js/summernote-zh-CN.js"></script>

<div class="app-content ng-scope">
  <div class="app-content-body fade-in-up ng-scope" >
  
   <div class="ng-scope">
    <div class="bg-light lter b-b wrapper-md ng-scope">
        <h1 class="m-n font-thin h3">七夕家装节会员卡</h1>
    </div>
    <div class="wrapper-md ng-scope">
      <div class="panel panel-default">
        <div class="panel-heading">七夕家装节会员卡
        {% if page <> '' %}
        <span class="label bg-info"><?php echo $page['totalRows']?> 条记录</span>
        {% endif %}
        </div>
        <div class="table-responsive">
          <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
          <div class="row">
                <div class="row wrapper">
                <form action="/admin/activecode/search" method="post">
                  <div class="col-sm-5 m-b-xs">
                    <select class="input-sm form-control w-sm inline v-middle" name="select" id="select">
                      <option value="city" {% if select == 'city' %}selected{% endif %}>城市</option>
                      <option value="card_number" {% if select == 'card_number' %}selected{% endif %}>卡号</option>
                      <option value="phone" {% if select == 'phone' %}selected{% endif %}>电话</option>
                      <option value="openid" {% if select == 'openid' %}selected{% endif %}>微信识别号</option>
                      <option value="money_status" {% if select == 'money_status' %}selected{% endif %}>红包金额</option>
                      <option value="id" {% if select == 'id' %}selected{% endif %}>v卡号段</option>
                    </select>
                    <input type="text" class="input-sm form-control search" placeholder="请输入搜索条件" name="search" value="{{ search }}">
                    <button class="btn btn-sm btn-default">搜索</button>                
                  </div>
                 </form>
                  <div class="col-sm-4">
                  </div>
                  <div class="col-sm-3">
                    <div class="input-group">
                      <span class="input-group-btn">
                        <a href="bmtable_xls"><button class="btn btn-sm btn-default" type="button">导出数据表</button></a>
                      </span>
                    </div>
                  </div>
                </div>
          </div>
          <table class="table table-striped m-b-none dataTable no-footer">
            <thead>
              <tr>
                  <th style="width: 200px;" class="sorting_asc" rowspan="1" colspan="1">城市</th>
                  <th style="width: 250px;" class="sorting" rowspan="1" colspan="1">卡号</th>
                  <th style="width: 150px;" class="sorting" rowspan="1" colspan="1">姓名</th>
                  <th style="width: 250px;" class="sorting" rowspan="1" colspan="1">电话</th>
                  <th style="width: 150px;" class="sorting" rowspan="1" colspan="1">金额</th>
                  <th style="width: 250px;" class="sorting" rowspan="1" colspan="1">微信名</th>
                  <th style="width: 300px;" class="sorting" rowspan="1" colspan="1">微信识别号</th>
                  <th style="width: 250px;" class="sorting" rowspan="1" colspan="1">激活时间</th>
              </tr>
            </thead>
            <tbody>
            {% for k in list %}
                <tr class="odd">
                    <td class="sorting_1">{{ k['city'] }}</td>
                    <td>{{ k['card_number'] }}</td>
                    <td>{{ k['name'] }}</td>
                    <td>{{ k['phone'] }}</td>
                    <td>{{ k['money_status'] }}</td>
                    <td>{{ k['wechaname'] }}</td>
                    <td>{{ k['openid'] }}</td>
                    <td>{{ k['mem_active'] }}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
          {% if page <> '' %}
          <?php $this->partial("index/page")?>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(function(){
$("#select").click(function(){
	var type = $(this).val();
	if(type == 'time'){
		$(".search").hide();
		$(".search_time").show();
	}
})
})
</script>
<script type="text/javascript">

$(document).ready(function() {
	
	$('.form_datetime').datetimepicker({
        language:  'zh-CN',
        linkFormat:'yyyy-mm-dd',
        weekStart: 0,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: true,
		startView: 2,
		minView: 3,
		forceParse: 0,
        showMeridian: 1,
    });
	
	var bar = [ 
		['style', ['bold', 'italic', 'underline', 'clear'] ],
		['font', ['strikethrough'] ],
		['fontsize', ['fontsize'] ],
		['color', ['color'] ],
		['para', ['ul', 'ol', 'paragraph'] ],
		['height', ['height']]
	]	
	
	$('#desc').summernote({toolbar:bar,height:200,width:600,lang:'zh-CN'});
	var sHTML = $('#desc').code();
	
});

</script>
<?php $this->partial("index/footer")?>