<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<link href="/admin/css/summernote.css" rel="stylesheet">
<script src="/admin/js/summernote.min.js"></script>
<script src="/admin/js/summernote-zh-CN.js"></script>

<div class="app-content ng-scope">
  <div class="app-content-body fade-in-up ng-scope" >
  
   <div class="ng-scope">
    <div class="bg-light lter b-b wrapper-md ng-scope">
        <h1 class="m-n font-thin h3">七夕家装节-返现红包布点数据表</h1>
    </div>
    <div class="wrapper-md ng-scope">
      <div class="m-b-sm">
        <div class="btn-group" ng-init="radioModel = 'Male'">
          <a href="/admin/hongbao/index"><label class="btn btn-sm btn-info ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'Male'"><i class="fa fa-check text-active"></i>发放/领取</label></a>
          <a href="/admin/hongbao/record"><label class="btn btn-sm btn-success ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'Female'"><i class="fa fa-check text-active"></i>详情</label></a>
          <a href="/admin/hongbao/use"><label class="btn btn-sm btn-primary ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'N/A'"><i class="fa fa-check text-active"></i>红包使用情况</label></a>
          <a href="/admin/hongbao/budian"><label class="btn btn-sm btn-danger ng-untouched ng-valid ng-dirty active ng-valid-parse" ng-model="radioModel" btn-radio="'N/A'"><i class="fa fa-check text-active"></i>数据布点</label></a>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">七夕家装节返现红包布点数据表
        <span class="label bg-info"></span>
        </div>
        <div class="table-responsive">
          <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
          <div class="row">
                <div class="row wrapper">
                  <div class="col-sm-4">
                  </div>
<!--                   <div class="col-sm-3">
                    <div class="input-group">
                      <span class="input-group-btn">
                        <button class="btn btn-sm btn-default" type="button"><a href="bmtable_xls11">导出数据表</a></button>
                      </span>
                    </div>
                  </div> -->
                </div>
          </div>
          <table class="table table-striped m-b-none dataTable no-footer">
            <thead>
              <tr>
                  <th style="width: 233px;" class="sorting_asc" rowspan="1" colspan="1">布点位置</th>
                  <th style="width: 250px;" class="sorting" rowspan="1" colspan="1">点击数</th>
              </tr>
            </thead>
            <tbody>
            {% for k in count %}
                <tr class="odd">
                    <td class="sorting_1">
                    {% if k['btn_id'] == 1 %}自己领一个
                    {% elseif k['btn_id'] == 2 %}分享再领一张
                    {% else %}我要报名
                    {% endif %}
                    </td>
                    <td>{{ k['num'] }}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(function(){
//$('#myModal').modal('toggle');
$("#select").click(function(){
	var type = $(this).val();
	if(type == 'time'){
		$(".search").hide();
		$(".search_time").show();
	}
})
})
</script>
<script type="text/javascript">

$(document).ready(function() {
	
	$('.form_datetime').datetimepicker({
        language:  'zh-CN',
        linkFormat:'yyyy-mm-dd',
        weekStart: 0,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: true,
		startView: 2,
		minView: 3,
		forceParse: 0,
        showMeridian: 1,
    });
	
	var bar = [ 
		['style', ['bold', 'italic', 'underline', 'clear'] ],
		['font', ['strikethrough'] ],
		['fontsize', ['fontsize'] ],
		['color', ['color'] ],
		['para', ['ul', 'ol', 'paragraph'] ],
		['height', ['height']]
	]	
	
	$('#desc').summernote({toolbar:bar,height:200,width:600,lang:'zh-CN'});
	var sHTML = $('#desc').code();
	
});

</script>
<?php $this->partial("index/footer")?>