<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<link href="/admin/css/summernote.css" rel="stylesheet">
<script src="/admin/js/summernote.min.js"></script>
<script src="/admin/js/summernote-zh-CN.js"></script>

<div class="app-content ng-scope">
  <div class="app-content-body fade-in-up ng-scope" >
  
   <div class="ng-scope">
    <div class="bg-light lter b-b wrapper-md ng-scope">
        <h1 class="m-n font-thin h3">七夕家装节-返现红包数据表</h1>
    </div>
    <div class="wrapper-md ng-scope">
      <div class="m-b-sm">
        <div class="btn-group" ng-init="radioModel = 'Male'">
          <a href="/admin/hongbao/index"><label class="btn btn-sm btn-info ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'Male'"><i class="fa fa-check text-active"></i>发放/领取</label></a>
          <a href="/admin/hongbao/record"><label class="btn btn-sm btn-success ng-untouched ng-valid ng-dirty active ng-valid-parse" ng-model="radioModel" btn-radio="'Female'"><i class="fa fa-check text-active"></i>详情</label></a>
          <a href="/admin/hongbao/use"><label class="btn btn-sm btn-primary ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'N/A'"><i class="fa fa-check text-active"></i>红包使用情况</label></a>
          <a href="/admin/hongbao/budian"><label class="btn btn-sm btn-danger ng-untouched ng-valid ng-dirty" ng-model="radioModel" btn-radio="'N/A'"><i class="fa fa-check text-active"></i>数据布点</label></a>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">七夕家装节返现红包数据表（共 {{ count }} 人领取了红包）
        <span class="label bg-info"></span>
        </div>
        <div class="table-responsive">
          <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
          <div class="row">
                 <form action="/admin/hongbao/record_search" method="post">
                  <div class="col-sm-5 m-b-xs">
                    <select class="input-sm form-control w-sm inline v-middle" name="select" id="select">
                      <option value="from_phone" {% if select == 'from_phone' %}selected{% endif %}>红包发起人</option>
                      <option value="phone" {% if select == 'phone' %}selected{% endif %}>红包领取人</option>
                      <option value="time" {% if select == 'add_time' %}selected{% endif %}>领取时间</option>
                    </select>
                    {% if select != 'verify_time' %}
                    <input type="text" class="input-sm form-control search" placeholder="请输入搜索条件" name="search" value="{{ search }}">
					{% endif %}
					<div class="form-group form-group-sm search_time" style="{% if select != 'verify_time' %}display: none{% endif %}">
					    <div class="input-group date form_datetime" data-date-format="yyyy-mm-dd" data-link-field="starttime">
							<input class="form-control" size="16" type="text" value="{{ search }}" readonly>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
						</div>
						<input type="hidden" id="starttime" name="time" value="{{ search }}" />
					</div>
                    <button class="btn btn-sm btn-default">搜索</button>                
                  </div>
                 </form>
                <div class="row wrapper">
                  <div class="col-sm-3">
                    <div class="input-group">
                      <span class="input-group-btn">
                        <button class="btn btn-sm btn-default" type="button"><a href="record_bmtable_xls">导出数据表</a></button>
                      </span>
                    </div>
                  </div>
                </div>
          </div>
          <table class="table table-striped m-b-none dataTable no-footer">
            <thead>
              <tr>
                  <th style="width: 120px;" class="sorting_asc" rowspan="1" colspan="1">红包发起人</th>
                  <th style="width: 120px;" class="sorting" rowspan="1" colspan="1">红包领取人</th>
                  <th style="width: 80px;" class="sorting" rowspan="1" colspan="1">金额</th>
                  <th style="width: 80px;" class="sorting" rowspan="1" colspan="1">券号</th>
                  <th style="width: 150px;" class="sorting" rowspan="1" colspan="1">领取时间</th>
                  <th style="width: 150px;" class="sorting" rowspan="1" colspan="1">验证时间</th>
                  <th style="width: 150px;" class="sorting" rowspan="1" colspan="1">状态</th>
              </tr>
            </thead>
            <tbody>
            {% for k in list %}
                <tr class="odd">
                    <td class="sorting_1">{{ k['from_phone'] }}</td>
                    <td>
                    {{ k['phone'] }}
                    {% if k['is_bm'] == 1%}
                    <span class="label bg-success">已报名</span>
                    {% else %}
                    <span class="label bg-danger">未报名</span>
                    {% endif %}
                    </td>
                    <td>{{ k['total'] }}</td>
                    <td>{{ k['sn'] }}</td>
                    <td>
                    {% if k['add_time'] != 0 %}
                    {{ date('Y-m-d H:i:s',k['add_time']) }}
                    {% endif %}
                    </td>
                    <td>
                    {% if k['verify_time'] != 0 %}
                    {{ date('Y-m-d H:i:s',k['verify_time']) }}
                    {% endif %}
                    </td>
                    <td>
                    {% if k['state'] == 1 %}<span class="label bg-danger">未验证</span>
                    {% elseif k['state'] == 2 %}<span class="label bg-warning">正在验证</span>
                    {% else %}<span class="label bg-success">已验证</span>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
          {% if page <> '' %}
          <?php $this->partial("index/page")?>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(function(){
$("#select").click(function(){
	var type = $(this).val();
	if(type == 'time'){
		$(".search").hide();
		$(".search_time").show();
	}
})
})
</script>
<script type="text/javascript">

$(document).ready(function() {
	
	$('.form_datetime').datetimepicker({
        language:  'zh-CN',
        linkFormat:'yyyy-mm-dd',
        weekStart: 0,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: true,
		startView: 2,
		minView: 3,
		forceParse: 0,
        showMeridian: 1,
    });
	
	var bar = [ 
		['style', ['bold', 'italic', 'underline', 'clear'] ],
		['font', ['strikethrough'] ],
		['fontsize', ['fontsize'] ],
		['color', ['color'] ],
		['para', ['ul', 'ol', 'paragraph'] ],
		['height', ['height']]
	]	
	
	$('#desc').summernote({toolbar:bar,height:200,width:600,lang:'zh-CN'});
	var sHTML = $('#desc').code();
	
});

</script>
<?php $this->partial("index/footer")?>