<!DOCTYPE html PUBLIC "-//W3C//DTD html 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="IE=11.0000" http-equiv="X-Ua-Compatible">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<title>登录</title>
<script src="/common/js/jquery-2.1.4.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="/admin/css/login.css" type="text/css"/>
<script type="text/javascript">
$(document).ready(function(){
	//得到焦点
	$("#password").focus(function(){
		$("#left_hand").animate({
			left: "150",
			top: " -38"
		},{step: function(){
			if(parseInt($("#left_hand").css("left"))>140){
				$("#left_hand").attr("class","left_hand");
			}
		}}, 2000);
		$("#right_hand").animate({
			right: "-64",
			top: "-38px"
		},{step: function(){
			if(parseInt($("#right_hand").css("right"))> -70){
				$("#right_hand").attr("class","right_hand");
			}
		}}, 2000);
	});
	//失去焦点
	$("#password").blur(function(){
		$("#left_hand").attr("class","initial_left_hand");
		$("#left_hand").attr("style","left:100px;top:-12px;");
		$("#right_hand").attr("class","initial_right_hand");
		$("#right_hand").attr("style","right:-112px;top:-12px");
	});

	$('#bm').click(function(){
		var username = $("#username").val();
		var password = $("#password").val();
		if(!username){
			$("#tips").html("");
			$("#tips").html('用户名不能为空');return;
		}
		if(!password){
			$("#tips").html("");
			$("#tips").html('请输入密码');return;
		}
		$.ajax({
			async:false,
		 	url: '/admin/login/login',
		 	data: {username:username, password:password},
		 	type: 'post',
		 	dataType:'json',
		 	success:function(result){
		 		if(parseInt(result.errcode)){
		 			$("#tips").html(result.errmsg);return;
		 		} else {
		 			location.href = "/admin/index/index";
			 	}
		 	},
		 	error:function(){
		 		$("#tips").html("");
		 		$("#tips").html('服务器繁忙，请刷新或退出重试！');return;
			}
		});
	});
});
</script>
</head>

<body>
<div class="top_div"></div>
<div style="background: rgb(255, 255, 255); margin: -100px auto auto; border: 1px solid rgb(231, 231, 231); border-image: none; width: 400px; height: 200px; text-align: center;">
    <div style="width: 165px; height: 96px; position: absolute;">
        <div class="tou"></div>
        <div class="initial_left_hand" id="left_hand"></div>
        <div class="initial_right_hand" id="right_hand"></div>
    </div>
        <P style="padding: 30px 0px 10px; position: relative;">
            <span class="u_logo"></span>
            <input class="ipt" id="username" type="text" placeholder="请输入用户名" value=""> 
        </P>
        <P style="position: relative;">
            <span class="p_logo"></span>         
            <input class="ipt" id="password" type="password" placeholder="请输入密码" value="">   
        </P>
    <div style="height: 50px; line-height: 50px; margin-top: 30px; border-top-color: rgb(231, 231, 231); border-top-width: 1px; border-top-style: solid;">
        <P style="margin: 0px 35px 20px 45px;">
               <!-- <span style="float: left;"><a style="color: rgb(204, 204, 204);" href="#">忘记密码?</a></span> -->
               <span id="tips"></span>
               <span style="float: right;">
               <!-- <a style="color: rgb(204, 204, 204); margin-right: 10px;" href="#">注册</a> -->
               <a style="background: rgb(0, 142, 173); padding: 7px 10px; border-radius: 4px; border: 1px solid rgb(26, 117, 152); border-image: none; color: rgb(255, 255, 255); font-weight: bold;" href="javascript:void(0)" id="bm">登录</a> 
               </span>
        </P>
    </div>
</div>
<div style="text-align:center;">www.yoju360.com</div>
</body>
</html>
