<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="front-end technicist" content="jinger" />
	<title>七夕家装节-天天有礼</title>
	<meta name="keywords" content="七夕家装节-天天有礼">
	<meta name="description" content="七夕家装节-天天有礼">
	<meta name="front-end technicist" content="jinger">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />

	<link type="text/css" rel="stylesheet" href="/tiger/css/layout.css?vid=3.0" media="all" />
	<script type="text/javascript" src="/tiger/js/jquery-1.10.2.js"></script>
	
 </head>

 <body class="prd-by">
 	<div class="prd-bg">
		
		<div class="prd-bj">
			<div class="prd-pic">
				<div class="prd-end">
					<div class="prd-end-con">已送完</div>
				</div>
				<div class="prd-die">
					<div class="prd-die-l"><p>10000 积分/对</p></div>
					<div class="prd-die-m"><p>|</p></div>
					<div class="prd-die-r" zdy="七夕情侣公仔小七+小夕" data="1"><p>兑换</p></div>
				</div>
				<img src="/tiger/images/prd4.jpg" width="100%">
			</div>
			<div class="prd-con">
				<div class="prd-con-left" style="font-size: 14px;">
					<p>剩余</p>
					<p><span class="B-font">{{giftList[0]['quantity']}}</span>对</p>
				</div>
				<div class="prd-con-middle">
					<div><table class="shuxian"><tr><td valign="top"></td></tr></table></div>
				</div>
				<div class="prd-con-right">
					<p class="B-J-font">七夕情侣公仔小七+小夕</p>
					<p>萌哒哒的七夕情侣公仔，七夕礼物必备</p>
				</div>
			</div>
		</div>

		<div class="prd-bj">
			<div class="prd-pic">
				<div class="prd-end">
					<div class="prd-end-con">已送完</div>
				</div>
				<div class="prd-die">
					<div class="prd-die-l"><p>20000 积分/个</p></div>
					<div class="prd-die-m"><p>|</p></div>
					<div class="prd-die-r" zdy="20元现金红包装修基金" data="2"><p>兑换</p></div>
				</div>
				<img src="/tiger/images/prd5.jpg" width="100%">
			</div>
			<div class="prd-con">
				<div class="prd-con-left">
					<p>剩余</p>
					<p><span class="B-font">{{giftList[1]['quantity']}}</span>个</p>
				</div>
				<div class="prd-con-middle">
					<div><table class="shuxian"><tr><td valign="top"></td></tr></table></div>
				</div>
				<div class="prd-con-right">
					<p class="B-J-font">20元现金红包</p>
					<p>我带着你，你带着钱，我们一起去七夕家装节</p>
				</div>
			</div>
		</div>


		<div class="prd-bj">
			<div class="prd-pic">
				<div class="prd-end">
					<div class="prd-end-con">已送完</div>
				</div>
				<div class="prd-die">
					<div class="prd-die-l"><p>30000 积分/套</p></div>
					<div class="prd-die-m"><p>|</p></div>
					<div class="prd-die-r" zdy="汝窑天青烘云托月茶壶套组" data="3"><p>兑换</p></div>
				</div>
				<img src="/tiger/images/prd1.jpg" width="100%">
			</div>
			<div class="prd-con">
				<div class="prd-con-left">
					<p>剩余</p>
					<p><span class="B-font">{{giftList[2]['quantity']}}</span>套</p>
				</div>
				<div class="prd-con-middle">
					<div><table class="shuxian"><tr><td valign="top"></td></tr></table></div>
				</div>
				<div class="prd-con-right">
					<p class="B-J-font">汝窑天青烘云托月茶壶套组</p>
					<p>享受生活品味人生必备</p>
				</div>
			</div>
			
		</div>

		<div class="prd-bj">
			<div class="prd-pic">
				<div class="prd-end">
					<div class="prd-end-con">已送完</div>
				</div>
				<div class="prd-die">
					<div class="prd-die-l"><p>40000 积分/个</p></div>
					<div class="prd-die-m"><p>|</p></div>
					<div class="prd-die-r" zdy="AO史密斯厨下反渗透净水机AR125-B1" data="4"><p>兑换</p></div>
				</div>
				<img src="/tiger/images/prd2.jpg" width="100%">
			</div>
			<div class="prd-con">
				<div class="prd-con-left">
					<p>剩余</p>
					<p><span class="B-font">{{giftList[3]['quantity']}}</span>个</p>
				</div>
				<div class="prd-con-middle">
					<div><table class="shuxian"><tr><td valign="top"></td></tr></table></div>
				</div>
				<div class="prd-con-right">
					<p class="B-J-font">AO史密斯厨下反渗透净水机AR125-B1</p>
					<p>智能滤芯，水质掌握更贴心</p>
				</div>
			</div>
		</div>

		<div class="prd-bj">
			<div class="prd-pic">
				<div class="prd-end">
					<div class="prd-end-con">已送完</div>
				</div>
				<div class="prd-die">
					<div class="prd-die-l"><p>50000 积分/个</p></div>
					<div class="prd-die-m"><p>|</p></div>
					<div class="prd-die-r" zdy="A.O史密斯电热水器CEWH60-K6" data="5"><p>兑换</p></div>
				</div>
				<img src="/tiger/images/prd3.jpg" width="100%">
			</div>
			<div class="prd-con">
				<div class="prd-con-left">
					<p>剩余</p>
					<p><span class="B-font">{{giftList[4]['quantity']}}</span>个</p>
				</div>
				<div class="prd-con-middle">
					<div><table class="shuxian"><tr><td valign="top"></td></tr></table></div>
				</div>
				<div class="prd-con-right">
					<p class="B-J-font">A.O史密斯电热水器CEWH60-K6</p>
					<p>即开即洗，无限畅浴，热水再也不用等</p>
				</div>
			</div>
		</div>

		

		<br/>
		<br/>
		<div class="producnt-bg">
			<div><p>点击空白处返回</p></div>
		</div>
		<div class="product-tan">
			<div class="product-tan-bg">
				<div class="product-tilte"><p></p></div>
				<div class="product-con">
					<div><input type="text" placeholder="姓名"  id="name"/></div>
					<div><input type="text" placeholder="手机号码"  id="phone"/></div>
					<div><input type="text" placeholder="收货地址" id="address" /></div>
				</div>
				<div>
					<input type="button" value="提交" class="product-btn"  id="tj" />
				</div>
			</div>
		</div>
		
 	</div>
 	<script type="text/javascript">
$(function(){
	 		var prd=$('.prd-bj');
	 		prd.each(function(index){
	 			if($(this).find('.prd-con-left span').text()=='0')
	 			{
	 				$(this).find('.prd-end').css('display','block');
	 			}
	 		})

	 	var _gg=$(".product-tan");
        var _bg = $(".producnt-bg");
	 	var prizeId;
		$(".prd-die-r").click(function(){
        	var _con=$(this).attr('zdy');
        	prizeId=$(this).attr('data');
        	
        	$('.product-tilte p').html(_con);
        	_bg.fadeIn();
        	_gg.fadeIn();

        	
        });

	 		_bg.click(function(){
	            _bg.fadeOut();
	            _gg.fadeOut();
			});
			
        	$("#tj").click(function(){
				var name=$("#name").val();
				var phone=$("#phone").val();
				var address=$("#address").val();
				var smTag = true;
				var ii = 0;
        		$.ajax({
                	async:false,
                    url: '/phone/tigerprize/submitinfo',
                    type: "post",
                    data:{name:name,phone:phone,address:address,prizeId:prizeId},
                    dataType:'json',
                    success:function(result){
                    	ii++;
                        console.log(ii);
                    	if(result.errcode != 0){
                            alert(result.errmsg);
                            
                            smTag = false;
                            return false;
                        }else{
                        	alert(result.errmsg);
                            return false;
                        }
                    }
                });
                if(smTag)
                {
		            _bg.fadeOut();
		            _gg.fadeOut();
		            location.reload() 
                }
			});
});
 	</script>	
  	
 </body>
</html>
