<!--专题 通用头部 -->
<style type="text/css">
     @charset "utf-8";
   body{font: 12px/1.7 "Microsoft YaHei" "SimSun" "Hiragino Sans GB";margin:0;width: 100%;}
    /*通用头部*/
    .topnav{
    padding:0 0px;height:36px;background:#000;background:rgba(0,0,0,0.85);
    position:fixed;_position:absolute;top:0;left:0;z-index:9999;width:100%;
    box-shadow:0px 3px 8px rgba(0,0,0,0.3); 
    }
    .topnav .logo{display:block;position:absolute;left:0;top:5px;width:181px;height:26px;background:url('http://zt.jia360.com/public/images/logo.png') no-repeat;_background:transparent;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://zt.jia360.com/public/images/logo.png',sizingMethod='scale');overflow:hidden;text-indent:-9999px;}
    .mininav{width:1000px;height:30px;margin:0 auto;position:relative;z-index:999999}
    .mininav,.mininav a,.mininav a:link ,.mininav .hychannel p.up,.mininav .hychannel ul a,.mininav .hychannel ul a:link{color:#ccc}
    .mininav a:hover ,.mininav .hychannel ul a:hover{color:#fff;transition: all 0.5s;-moz-transition: all 0.5s;-webkit-transition: all 0.5s;-o-transition: all 0.5s;}
    .mininav  a:hover{text-decoration:underline;}
    .mininav .yt{display:inline-block;float:left;height:30px;border-left:1px solid #ebebeb;border-right:1px solid #ebebeb;line-height:30px;padding:0 10px;}
    .mininav .mr{margin-left:185px;font-family:"SimSun","宋体";}
    .mininav .l{float:right;line-height:36px;}
    .mininav .nt{float:right;padding:0 5px;line-height:36px;position:relative;z-index:99999}
    .mininav .cm{float:right;width:66px;height:36px;position:relative}
    .mininav .cm p{width:66px;height:36px;line-height:36px;text-indent:6px;background:url('http://zt.jia360.com/public/images/yt_ico_c.png') 40px 6px no-repeat;color:#fff;cursor:pointer;position:absolute;z-index:99999;left:0;top:0;}
    .mininav .cmhover p{background:url('http://zt.jia360.com/public/images/yt_ico_c.png') 40px -28px no-repeat;}
    .tabcity{display:none;width:410px;padding:0 20px;color:#9b763b;position:absolute;right:0;top:34px;z-index:999999;overflow:hidden}
    .tabcity .ht{width:400px;height:30px;line-height:30px;font-weight:bold;position:relative;z-index:9999}
    .tabcity .ht .l{display:block;width:332px;height:10px;overflow:hidden;border-bottom:1px solid #9b763b;position:absolute;right:0;top:6px}
    .tabcity .ht a,.tabcity .ht b{line-height:30px;font-weight:normal}
    .tabcity .ht span b{margin-right:5px;}
    .tabcity .cityall{height:120px;}
    .tabcity .citylist{float:left;width:68px;position:relative;z-index:9999}
    .tabcity .citylist li{line-height:20px;color:#999}
    .tabcity .citylist li a{color:#333}
    .tabcity .citylist li b{color:#af874b}
    .tabcity .citylist li span{padding-right:8px;font-size:14px;font-weight:bold;}
    .tabcity .citylist li span.n{font-size:12px;font-weight:normal;}
    .tabcity .tcmask{width:450px;height:260px;background:#f5f0e8;opacity:0.9;filter:alpha(opacity=90);position:absolute;left:0;top:2px;z-index:999}
    .mininav .hychannel{float:right;width:78px;height:36px;position:relative;top:0px;z-index:999999}
    .mininav .hychannel p{width:78px;height:36px;line-height:36px;text-indent:8px;background:url('http://zt.jia360.com/public/images/tico.png') 60px 9px no-repeat;cursor:pointer;position:absolute;z-index:99999;left:0;top:0;  color: #ccc;  -webkit-margin-before: 0;-webkit-margin-after: 0;}
    .mininav .hychannel p{height:36px;transition: all 0.5s;-moz-transition: all 0.5s;-webkit-transition: all 0.5s;-o-transition: all 0.5s;}
    .mininav .hychannel p.up{background:url('http://zt.jia360.com/public/images/tico.png') 60px -18px no-repeat;}
    .mininav .hychannel ul.tg{-webkit-transform: scale(1);-moz-transform: scale(1);-ms-transform: scale(1);opacity: 1;display: block;}
    .mininav .hychannel ul{display:none\9;width:310px;padding:5px 10px;background: rgba(0,0,0,.6);background:#333\9;position:absolute;z-index:999;right:-3px;top:35px;border: 1px solid #000;border-top:none;opacity: 0;-webkit-transform: scale(0);-webkit-transition: all 0.3s cubic-bezier(.4,.83,.32,1.33);-webkit-transform-origin: right top;-moz-transform: scale(0);-moz-transition: all 0.3s cubic-bezier(.4,.83,.32,1.33);-moz-transform-origin: right top;-ms-transform: scale(0);-ms-transition: all 0.3s cubic-bezier(.4,.83,.32,1.33);-ms-transform-origin: right top;box-shadow: 0 1px 5px rgba(0,0,0,.2);}
    .mininav .hychannel ul.whz{width:140px;}
    .mininav .hychannel ul a{display:inline-block;height:22px;line-height:22px;padding:0 7px;}   
</style>
<script type="text/javascript">
$(function(){
   //亚太传媒
    var yt = yt || {};

    //头部模块
    yt.header = function () {

        //下拉菜单
        var bindHyChannel = function () {
            var $hy = $("#hychannel"),
                $p = $hy.find('p'),
                $ul = $hy.find('ul');

            $hy.hover(function () {
                $p.toggleClass('up');
                $ul.toggleClass('tg');
            });
        };
        //浮动top
        var bindTopNav = function () {

            var $topNav = $("#topNav"),
                $doc = $(document),
                htop = 0,
                height = 36,
                isDown = false;
            $(window).scroll(function () {
                var _htop = $doc.scrollTop(),
                _isDown = !!(_htop - htop > 0),
                _top = _isDown ? -height : 0;
                htop = _htop;
                if (_isDown == isDown) {
                    return;
                }
                isDown = _isDown;
                $topNav.stop().animate({ top: _top }, 500);
            });
        };
        //init
        bindHyChannel();
        bindTopNav();

    };
    yt.init = function () {
       yt.header();
    };

    yt.init();
})
</script>
<div class="header topnav" id="topNav" >
    <div class="mininav">
        <a href="http://www.jia360.com/" target="_blank" class="logo" title="腾讯网亚太家居·腾讯家居<">腾讯网亚太家居_腾讯家居</a>
        <div class="mr">
            <!--<span id="morecity" class="cm">
                <p>城市站</p>
                <div class="tabcity" id="tabcity"></div>
            </span>
            <span class="l">|</span>-->
            <span id="hychannel" class="hychannel">
                <p>产品中心</p>
                <ul>
                    <a href="http://www.jia360.com/jiaju/" target="_blank">家具</a>
                    <a href="http://www.jia360.com/weiyu/" target="_blank">卫浴</a>
                    <a href="http://www.jia360.com/cizhuan/" target="_blank">瓷砖</a>
                    <a href="http://www.jia360.com/yigui/" target="_blank">衣柜</a>
                    <a href="http://www.jia360.com/chufang/" target="_blank">厨房</a>
                    <a href="http://www.jia360.com/huwai/" target="_blank">户外</a>
                    <a href="http://www.jia360.com/muwu/" target="_blank">木屋</a>
                    <a href="http://www.jia360.com/diaoding/" target="_blank">吊顶</a>
                    <a href="http://www.jia360.com/shicai/" target="_blank">石材</a>
                    <a href="http://www.jia360.com/zhujiaju/" target="_blank">竹家居</a>
                    <a href="http://www.jia360.com/diban/" target="_blank">地板</a>
                    <a href="http://www.jia360.com/menchuang/" target="_blank">门窗</a>
                    <a href="http://www.jia360.com/zhengmu/" target="_blank">整木</a>
                    <a href="http://www.jia360.com/hongmu/" target="_blank">红木</a>
                    <a href="http://www.jia360.com/jiashi/" target="_blank">家饰</a>
                    <a href="http://www.jia360.com/louti/" target="_blank">楼梯</a>
                    <a href="http://www.jia360.com/shuimian/" target="_blank">睡眠</a>
                    <a href="http://www.jia360.com/qiangzhi/" target="_blank">墙纸</a>
                    <a href="http://www.jia360.com/zhaoming/" target="_blank">照明</a>
                    <a href="http://www.jia360.com/gangmumen/" target="_blank">钢木门</a>
                    <a href="http://www.jia360.com/cainuo/" target="_blank">采暖</a>
                    <a href="http://www.jia360.com/shafa/" target="_blank">沙发</a>
                    <a href="http://www.jia360.com/jiafang/" target="_blank">家纺</a>
                    <a href="http://www.jia360.com/ditan/" target="_blank">地毯</a>
                    <a href="http://www.jia360.com/yuanyi/" target="_blank">园艺</a>
                    <a href="http://www.jia360.com/tuliao/" target="_blank">涂料</a>
                    <a href="http://www.jia360.com/wujin/" target="_blank">五金</a>
                    <a href="http://www.jia360.com/ertong/" target="_blank">儿童家具</a>
                </ul>
            </span>
            <span class="l">|</span>
            <a href="http://www.jia360.com/product/picture/" target="_blank" class="nt">图库</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/product/evaluation/" target="_blank" class="nt">评测</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/zhuanti/qgbcqc" target="_blank" class="nt">导购</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/product/fresh/" target="_blank" class="nt">新品</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/homelife/geomantic/" target="_blank" class="nt">风水</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/fitment/idea/" target="_blank" class="nt">配饰</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/fitment/college/" target="_blank" class="nt">案例库</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com:80/shejishi/index.html" target="_blank" class="nt">设计师</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/news/video/" target="_blank" class="nt">视频</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/zhuanti/" target="_blank" class="nt">专题</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/news/person/" target="_blank" class="nt">人物</a>
            <span class="l">|</span>
            <a href="http://news.jia360.com/" target="_blank" class="nt">新闻</a>
            <span class="l">|</span>
            <a href="http://www.jia360.com/" target="_blank" class="nt">首页</a>

        </div>
    </div>
</div>
<!-- end -->