<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>奥普全国店庆活动</title>
	<meta name="keywords" content="奥普全国店庆活动" />
	<meta name="description" content="奥普全国店庆活动" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
	<link rel="stylesheet" type="text/css"  href="/aupu/css/com.css?v=1.8" />
	<script type="text/javascript">
	var payDomain = '{{payDomain}}';
	</script>
</head>
<body>
	<div class="cn-spinner loading" id="loading">
		<div class="spinner">

			<div class="spinner-container container1">
				<div class="circle1"></div>
				<div class="circle2"></div>
				<div class="circle3"></div>
				<div class="circle4"></div>
			</div>
			<div class="spinner-container container2">
				<div class="circle1"></div>
				<div class="circle2"></div>
				<div class="circle3"></div>
				<div class="circle4"></div>
			</div>
			<div class="spinner-container container3">
				<div class="circle1"></div>
				<div class="circle2"></div>
				<div class="circle3"></div>
				<div class="circle4"></div>
			</div>
		</div>
	</div>

	<div class="swiper-container swiper-pages" id="swiper-container1">
		<div class="swiper-wrapper" id="wrapper">

			<div class="swiper-slide page-1 ps1">
				<div class="container">
					<div class="am logo">
						<img src="/aupu/images/logo.png"/>
					</div>
					<div class="am cityOpen">
						<span>{{ content['city'] }}站</span>
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/aupu/images/p1_1.png?v=2.1" />
						</div>
					</div>
					<!-- 					<div class="am am22">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img src="/aupu/images/p0.png" />
					</div>
				</div>
				-->
				<div class="am am4">
					<img src="/aupu/images/p1_2.png"></div>
				<div class="am am6">
					<p class="city">
						<span>{{ content['city'] }}站</span>
					</p>
					<p class="cy-time">
						<span>{{ content['time'] }}</span>
					</p>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="1"/>
				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<div class="swiper-slide page-2 ps2">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img src="/aupu/images/p2_1.png" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="2"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>
		<div class="swiper-slide page-3 ps3">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p33_1.png" />
					</div>
				</div>
				<div class="am am4">
					<div id="swiper2" class="swiper swiperStyle2">
						<div class="swiper-container">
							<div class="swiper-wrapper">
								<div class="swiper-slide">
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/1.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/2.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/3.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/4.png"/>
										<div class="price">
											<span>1</span>元
										</div>
									</div>
								</div>
								<div class="swiper-slide">
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/5.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/6.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/7.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/8.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
								</div>
								<div class="swiper-slide">
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/9.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/10.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/11.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/12.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
								</div>
								<div class="swiper-slide">
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/13.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/14.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/15.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/16.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
								</div>
								<div class="swiper-slide">
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/17.png" />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
									<div class="imgBox">
										<img src="/aupu/images/yiyuanqiang/default.png" data-src="/aupu/images/yiyuanqiang/18.png"  />
										<div class="price">
											<span>1</span>元
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="pagination"></div>
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="2"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>
		<div class="swiper-slide page-3 ps4">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png"  />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p3_1.png?v=2.0" />
					</div>
				</div>
				<div class="am am4">
					<div id="swiper3" class="swiper">
						<div class="swiper-container">
							<div class="swiper-wrapper">
								<div class="swiper-slide">
									<div class="lobox">
									<img src="/aupu/images/pd/default.png" data-src="/aupu/images/pd/s1.png?v=3.0" alt="">
									</div>
								</div>
								<div class="swiper-slide">
									<div class="lobox">
									<img src="/aupu/images/pd/default.png" data-src="/aupu/images/pd/s2.png?v=3.0" alt="">
									</div>
								</div>
								<div class="swiper-slide">
									<div class="lobox">
									<img src="/aupu/images/pd/default.png" data-src="/aupu/images/pd/s3.png?v=3.0" alt="">
									</div>
								</div>
							</div>
						</div>
						<div class="pagination"></div>
					</div>
				</div>
				<div class="am bmOpen">
					<img data-src="/aupu/images/btn2.png" class="click_btn"  data-id="3"/>
				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<!-- <div class="swiper-slide page-4 ps5">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p4_1.png?v=2.0" />
					</div>
				</div>
				<div class="am am4">
					<img data-src="/aupu/images/p4_2.png?v=2.0" alt=""></div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="4"/>
		
				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div> -->

		<div class="swiper-slide page-5 ps6">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" class="logo" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p5_1.png?v=2.0" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="5"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<div class="swiper-slide page-6 ps7">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" class="logo" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p6_1.png?v=2.0" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="6"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<div class="swiper-slide page-8 ps8">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" class="logo" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p7_1.png?v=2.0" />
					</div>
				</div>
				<div class="am am4">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p7_2.png?v=2.0" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="7"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<!-- <div class="swiper-slide page-9 ps9">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" class="logo" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p8_1.png?v=2.0" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="8"/>

				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div> -->

		<div class="swiper-slide page-10 ps10">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png"  />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am1">
					<img data-src="/aupu/images/p9_1.png?v=2.0"  />
				</div>
				<div class="am am2"></div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="9"/>
				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>

		<div class="swiper-slide page-11 ps11">
			<div class="container">
				<div class="am logo">
					<img src="/aupu/images/logo.png" class="logo" />
				</div>
				<div class="am cityOpen">
					<span>{{ content['city'] }}站</span>
				</div>
				<div class="am am2">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/p10_1.png?v=2.0" />
					</div>
				</div>
				<div class="am am4">
					<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
						<img data-src="/aupu/images/site/{{ content['city_code'] }}.png" />
					</div>
				</div>
				<div class="am bmOpen">
					<img src="/aupu/images/btn1.png?v=2.1" class="click_btn"  data-id="10"/>
				</div>
				<div class="am am3">（此券仅限指定奥普门店使用）</div>
			</div>
		</div>
	</div>
	<div class="pagination" id="pagination1"></div>
</div>
<!-- 下滑提示 -->
<div class="cn-slidetips next">
	<div class="slidetips">
		<a href="javascript:void(0);" title="NEXT" id="next">
			<img src="/aupu/images/next.png" />
		</a>
	</div>
</div>

<!-- 城市选择 -->

<div class="citySelect hide" id="citySelect">
	<div class="black_bg"></div>
	<div class="cityWarp">
		<div class="cityHead">
			<p class="cityClose">
				<span>{{ content['city'] }}站</span>
			</p>
		</div>
		<div class="cityBody">
			<p class="ip">
				我们猜您在：
				<span>{{ content['location_city'] }}</span>
			</p>
			{% if is_city <> '' %}
			<p class="grey">
				您当前选择的城市站为：
				<span style="font-weight: bold;color:#e70000">{{ content['city'] }}站</span>
			</p>
			{% else %}
			<p class="grey">
				我们为您推荐最近城市站：
				<span style="font-weight: bold;color:#e70000">{{ content['city'] }}站</span>
				，您也可以选择：
			</p>
			{% endif %}
			<div class="city cf">
				{% for k,key in city_list %}
				<a href="?city={{ key['city_code'] }}" {% if (k+1)%5 == 0 %}class="mr0"{% endif %}>{{ key['city'] }}</a>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

<!-- 报名页 -->
<div class="baoming hide" id="baoming">
	<div class="bmWarp">
		<div class="bmHead">
			<p class="lph">领取3199现金券</p>
			<p class="lpf hide">填写收票地址</p>
			<span class="bmClose">×</span>
		</div>
		<!-- 领票 -->
		<div class="lpForm">
			<p class="bmmsg">
				限量现金券抢夺中！已有
				<span class="bmnum">{{ count + 4000 }}</span>
				人领取成功
				<!-- 已有<span class="bmnum">{{ count }}</span>
			人成功领到门票 -->
		</p>
		<p>
			<input type="text" name="name" class="name" placeholder="请填写姓名" />
		</p>
		<p>
			<input type="number" name="tel" class="tel" placeholder="请填写手机号码" />
		</p>
		<p class="lpBtn false">领取</p>
	</div>
	<!-- 提交验证 -->
	<div class="bmForm hide">
		<p>
			<select id="area" class="area"></select>
		</p>
		<p>
			<input type="text" id="address" name="address" class="address" placeholder="请填写详细地址" />
		</p>
		<p class="mtBig">
			<input type="number" name="code" class="code" placeholder="请输入验证码" />
			<span class="getCode">获取验证码</span>
		</p>
		<input type="hidden" id="send_phone" value=""/>
		<input type="hidden" id="btn_id" value=""/>
		<input type="hidden" id="verify" value=""/>
		<p class="tips"></p>
		<p class="bmBtn false">提交验证</p>
	</div>
</div>
</div>

<!-- 报名成功页 -->
<div class="succeed hide" id="succeed">
<div class="am logo">
	<img src="/aupu/images/logo.png"/>
</div>
<div class="succeed-p">
	<img data-src="/aupu/images/succeed.png" class="succeedImg" />
</div>
<div class="succeedText1"></div>
<div class="am am4"></div>
<a class="ad" href="/phone/yiyuanqiang/index/9">

	<img data-src="/aupu/images/succeed1.jpg"  />
		
</a>
</div>

<!-- 通用提示 -->
<div class="comTips hide" id="comTips">
<div class="tipsWarp">
	<div class="tipsBody">提示</div>
	<div class="tipsClose">确认</div>
</div>
</div>

<!-- loading 2.0 -->
<div class="cn-spinner loading2 hide" id="loading2">
<div class="spinner-warp">
	<div class="spinner">
		<div class="spinner-container container1">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container2">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
		<div class="spinner-container container3">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
			<div class="circle4"></div>
		</div>
	</div>
</div>
</div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script src="/aupu/js/my.js?v=1.1"></script>
<script src="/common/js/jweixin-1.0.0.js"></script>
<script>
	//微信分享控制
	var code = {{ content['code'] }};
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
		var wxData = {
			"imgUrl":'{{domain}}/aupu/images/share.jpg',
			"link":'{{domain}}/phone/aupu/index',
			"desc":"5折购+抢特权—奥普全国店庆，免费预约到店戳这里！",
			"title":"5折购+抢特权—奥普全国店庆，免费预约到店戳这里！"
		};
		wx.onMenuShareAppMessage(wxData);
		wx.onMenuShareTimeline(wxData);
	});
</script>

<script src="/common/js/tongji.js"></script>
</body>
</html>