<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>2015天津优居家博会</title>
<meta name="keywords" content="2015天津优居家博会" />
<meta name="description" content="2015天津优居家博会" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/tianjin/mobile/css/com.css" />

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>

   <div class="swiper-container swiper-pages" id="swiper-container1">
        <div class="swiper-wrapper" id="wrapper">

			<div class="swiper-slide page-1 ps1">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2"/>
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/tianjin/mobile/images/p1_1.png?v=1.3" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="1"/>
					</div>
					<div class="am am3">主办方：优居网</div>
				</div>
			  </div>

			<div class="swiper-slide page-2 ps2">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img src="/tianjin/mobile/images/p2_1.png?v=1.2" />
						</div>
					</div>
					<div class="am am4">
						<div id="swiper1" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
									<div class="swiper-slide">
										<img src="/tianjin/mobile/images/cx/1.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/cx/2.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/cx/3.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/cx/4.png?v=1.0"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/cx/5.png?v=1.0"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/cx/6.png"  />
									</div>
								</div>
							</div>

							<div class="pagination"></div>
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="2"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-3 ps3">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2"  />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p3_1.png?v=1.2" />
						</div>
					</div>
					<div class="am am4">
						<div id="swiper2" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
									<div class="swiper-slide">
										<ul class="pd">
											<li><img src="/tianjin/mobile/images/yy/1.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/2.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/3.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/4.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/5.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/6.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/7.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/8.jpg"  /></li>
										</ul>
										<p class="text">产品以秒杀页面为主</p>
									</div>
									<div class="swiper-slide">
										<ul class="pd">
											<li><img src="/tianjin/mobile/images/yy/9.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/10.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/11.jpg"  /></li>
											<li><img src="/tianjin/mobile/images/yy/12.jpg"  /></li>
										</ul>
										<p class="text">产品以秒杀页面为主</p>
									</div>
								</div>
							</div>

							<div class="pagination"></div>
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="3"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-4 ps4">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p4_1.png?v=1.2" />
						</div>
					</div>
					<div class="am am4">
						<div id="swiper3" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
									<div class="swiper-slide">
										<img src="/tianjin/mobile/images/tg/1.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/tg/2.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/tg/3.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/tg/4.png"  />
									</div>
								
								</div>
							</div>

							<div class="pagination"></div>
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="4"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>

			<div class="swiper-slide page-5 ps5">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p5_1.png?v=1.2" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="5"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-6 ps6">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p6_1.png?v=1.2" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="6"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			<div class="swiper-slide page-7 ps7">
				<div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p7_1.png?v=1.2" />
						</div>
					</div>
					<div class="am am4">
						<div id="swiper4" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
									<div class="swiper-slide">
										<img src="/tianjin/mobile/images/logo/1.png"  />
									</div>
									<div class="swiper-slide">
										<img data-src="/tianjin/mobile/images/logo/2.png"  />
									</div>
								
								</div>
							</div>
							<div class="pagination"></div>
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="7"/>						
					</div>
					<div class="am am3">主办方：优居网</div>
				</div>
			</div>
			<div class="swiper-slide page-8 ps8">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p8_1.png?v=1.2" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="8"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
			
			<div class="swiper-slide page-9 ps9">
			  <div class="container">
					<div class="am logo">
						<img src="/tianjin/mobile/images/logo.png?v=1.2" class="logo" />
					</div>
					<div class="am am2">
						<div class="animation1 an1" data-item="an1" data-delay="200" data-animation1="bounceIn">
							<img data-src="/tianjin/mobile/images/p9_1.png?v=1.2" />
						</div>
					</div>
					<div class="am bmOpen">
						<img src="/tianjin/mobile/images/btn1.png?v=1.2" class="click_btn"  data-id="9"/>
						
					</div>
					<div class="am am3">主办方：优居网</div>
			  </div>
			</div>
	
              
       </div>
    </div>
    <!-- 下滑提示 -->
    <div class="cn-slidetips next">
  	    <div class="slidetips">
  	        <a href="javascript:void(0);" title="NEXT" id="next">
  	            <img src="/tianjin/mobile/images/next.png" />
  	        </a>
  	    </div>
  	</div>    
	

	<!-- 报名页 -->
	<div class="baoming hide" id="baoming">
		<div class="bmWarp">
			<div class="bmHead">
				<p class="lph">天津家博会0元领票</p>
				<p class="lpf hide">填写收票地址</p>
				<span class="bmClose">×</span>
			</div>
			<!-- 领票 -->
			<div class="lpForm">
			    <p class="bmmsg">已有<span class="bmnum">{{ count }}</span>人成功领到门票</p>
				<p><input type="text" name="name" class="name" placeholder="请填写姓名" /></p>
				<p><input type="number" name="tel" class="tel" placeholder="请填写手机号码" /></p>
				<p class="lpBtn false">提交领票</p>	
			</div>
			<!-- 提交验证 -->
			<div class="bmForm hide">
				<p>
					<select id="area" class="area">
						<option value="和平区">和平区</option>
					 	<option value="河西区">河西区</option>
						<option value="河东区">河东区</option>
						<option value="红桥区">红桥区</option>
						<option value="南开区">南开区</option>
					 	<option value="河北区">河北区</option>
						<option value="西青区">西青区</option>
						<option value="津南区">津南区</option>
						<option value="北辰区">北辰区</option>
					 	<option value="东丽区">东丽区</option>
						<option value="宝坻">宝坻</option>
						<option value="武清">武清</option>
						<option value="滨海新区">滨海新区</option>
						<option value="静海">静海</option>
						<option value="宁河">宁河</option>
						<option value="蓟县">蓟县</option>
						<option value="乡镇">乡镇</option>
					</select>
				</p>
				<p>
					<input type="text" id="address" name="address" class="address" placeholder="请填写详细地址" />
				</p>
				<p class="mtBig"><input type="number" name="code" class="code" placeholder="请输入验证码" /><span class="getCode">获取验证码</span>
				</p>
				<input type="hidden" id="send_phone" value=""/>
				<input type="hidden" id="btn_id" value=""/>
				<input type="hidden" id="verify" value=""/>
				<p class="tips"></p>				
				<p class="bmBtn false">提交验证</p>
			</div>
		</div>
	</div>

	<!-- 报名成功页 -->
	<div class="succeed hide" id="succeed">
		<!-- <div class="am logo">
			<img src="/tianjin/mobile/images/logo.png?v=1.2"/>
		</div>	 -->
		<div class="succeed-p">
		<img data-src="/tianjin/mobile/images/succeed.png" class="succeedImg" />
		</div>
		<div class="succeedText1">
			<p>恭喜您成功索得门票，工作人员会在24小时内电话回访您，核对邮寄门票的地址，请注意接听，祝您生活愉快！</p>
		</div>
		
		<div class="am am4">
			<a href="/phone/markdown/index/12?from=bm"><img src="/tianjin/mobile/images/12545656.png" /></a>
		</div>
	</div>
	

	<!-- 通用提示 -->
	<div class="comTips hide" id="comTips">
		<div class="tipsWarp">
			<div class="tipsBody">
				提示
			</div>
			<div class="tipsClose">
				确认
			</div>
		</div>
	</div>

	<!-- loading 2.0 -->
	<div class="cn-spinner loading2 hide" id="loading2">
		<div class="spinner-warp">
	        <div class="spinner">
	            <div class="spinner-container container1">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container2">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	            <div class="spinner-container container3">
	                <div class="circle1"></div>
	                <div class="circle2"></div>
	                <div class="circle3"></div>
	                <div class="circle4"></div>
	            </div>
	        </div>
	    </div>
    </div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script src="/common/js/tongji.js"></script>
<script src="/tianjin/mobile/js/my.js?v=1.0"></script>
<script src="/common/js/jweixin-1.0.0.js"></script>
<script>
	//微信分享控制
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
		var wxData = {
			"imgUrl":'{{domain}}/tianjin/mobile/images/share.jpg',
			"link":'{{domain}}/phone/tianjin/index',
			"desc":"免费领家博会门票 2015天津优居家博会 免费门票限量发放中，点击领取！",
			"title":"免费领家博会门票 2015天津优居家博会 免费门票限量发放中，点击领取！"
		};
		wx.onMenuShareAppMessage(wxData);
		wx.onMenuShareTimeline(wxData);
	});
</script>
</body>
</html>