<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>支付成功</title>
	<meta name="keywords" content="支付成功" />
	<meta name="description" content="支付成功" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
	<link rel="stylesheet" type="text/css"  href="/markdown/css/rank.css?v=2.0" />
	<script src="/common/js/jquery-2.1.4.min.js"></script>
	<style>
	.bg4{
    width: 100%;
    margin: 0 auto;
    background-color: #fff;
    border: 0px;

}

.head{
	width:100%;	

}

.title2{
	width: 100%;
	font-size: 14px;
	font-weight: bold;
	color:black;
	text-align: center;
	padding:4% 0 3% 0;
}

.b-cls{
	width: 10%;
	display: block;
	margin-top:-10%;
	padding: 1% 0 1% 2%;
	
	
}

.b-cls img{
	width:60%;
}

.fin{
	width:50%;
	margin:30px auto;
}

.fin img{
	width: 100%;
}
.order{
	width:50%;
	display:block;
	font-size:12px;
	margin:0 auto;
	color:#a8a8a8;
}

.p-ad{
	display:block;
	width: 95%;
	margin: 0 auto;
}

.p-ad img{
	width: 100%;
}

</style>
</head>
<body>
	<div class="bg4">
	    <div class="head">
			<div class="title2">支付成功</div>
			<a href="javascript:void(0);" class="b-cls"><img src="/markdown/images/back.png" alt=""></a>
        </div>

        <div class="fin">
	        <img src="/markdown/images/pay/fin.png" alt="">
	        <a href="{{payDomain}}/phone/pay/order" class="order">查看我的订单</a>
        </div>
		<a href="/phone/qixi/index.html&from=bangkan002" class="p-ad"><img src="/markdown/images/pay/p-banner.png" alt=""></a>
    </div>

</body>
</html>