	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<!-- 回到顶部 -->
		<div class="goToTop hide" id="goToTop">
			<div class="goToTopBg"></div>
			<span></span>
		</div>

	<!--通用提示弹窗-->
	<div class="generalTipsBox hide" id="generalTipsBox">
		<div class="generalTipsHead">
			<p>提示</p>
			<a class="generalTipsClose close">x</a>
		</div>
		<div class="generalTipsMain">
			<p class="tips">tips</p>
			<span class="generalTipsBtn generalTipsClose">关闭（<span class="time">3</span>s）</span>
		</div>
	</div>
	<!-- end -->
	<!-- 统计 -->
	<!-- 通用footer，建议抽出为一个文件，再每页引入 -->
	<link type="text/css" rel="stylesheet" href="{{pcHome}}/group/templates/css/footer.css" media="all">
	<script type="text/javascript" src="{{pcHome}}/head.php?act=footer"></script>
	<script type='text/javascript'>
		(function(){document.getElementById('___szfw_logo___').oncontextmenu =function(){return false;}})();
	</script>
	<!-- footer end -->
</body>
</html>