<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="front-end technicist" content="jinger" />
	<title>七夕总结</title>
	<meta name="keywords" content="七夕总结">
	<meta name="description" content="七夕总结">
	<meta name="front-end technicist" content="jinger">
	<link type="text/css" rel="stylesheet" href="/qxzj/css/layout.css?vid=1.3" media="all" />
 </head>

 <body>
  	<div class="main" id="b1">
		<div class="box1" >
			<div class="box1-live">
				<p>七夕家装节50个活动城市现场播报<span>8月22日-29日</span></p>
			</div>
			<div class="box1-1">
				<div class="box1-1-icon">
					<!-- <img src="images/icon1.png"> -->
				</div>
				<div class="box1-1-con" id="scrollDiv">
					<!-- <ul>
			            <li>
			            	<span>刘先生159****3421购买大自然地板</span>
			            	<span>刘先生159****3421购买大自然地板</span>
			            	<span>刘先生159****3421购买大自然地板</span>
			            </li>
			            <li>
			            	<span>刘先生159****3421购买大自然地板1</span>
			            	<span>刘先生159****3421购买大自然地板1</span>
			            	<span>刘先生159****3421购买大自然地板1</span>
			            </li>
			            <li>
			            	<span>刘先生159****3421购买大自然地板2</span>
			            	<span>刘先生159****3421购买大自然地板2</span>
			            	<span>刘先生159****3421购买大自然地板2</span>
			            </li>
			            <li>
			            	<span>刘先生159****3421购买大自然地板3</span>
			            	<span>刘先生159****3421购买大自然地板3</span>
			            	<span>刘先生159****3421购买大自然地板3</span>
			            </li>
			        </ul> -->
					
				</div>
			</div>
		</div>
		<div class="box2" >
			<div class="box2-1">
				<div class="box2-1-title"><a><img src="images/box2-xczj.jpg"></a></div>
			</div>
			<div class="box2-2" id="b2">
				<div class="box2-2-title"><img src="images/box2-hdzb.png"></div>
				<div class="box2-2-tag">
					<div class="box2-tag-hover"><p>8月22号</p></div>
					<div class="box2-tag-normal" style="margin-left: 5px;"><p>8月23号</p></div>
					<div class="box2-tag-normal" style="margin-left: 5px;"><p>8月29号</p></div>
				</div>
				<div class="box2-2-bg" id="live1"><!-- tag-1 -->
				<div class="gun" id="cn-run1">
				<ul id="ul-run1">
				{% for k,key in live_list1 %}
					<li class="box2-2-con">
						<p class="box2-2-con-title">【LIVE】{{ key['keyword'] }}：{{ key['title'] }}</p>
						<div class="box2-2-time">{{ key['time'] }}</div>
						<p class="box2-2-con-ct">{{ key['desc'] }}......</p>
						<div class="box2-2-btn"><a href="{{ key['link'] }}" target="_blank">详细</a></div>
						<hr style="border:1px dotted #666666" />
					</li>
				{% endfor %}
				</ul>
				</div>
				</div>

				<div class="box2-2-bg" id="live2" style="display:none"><!-- tag-2 -->
				<div class="gun" id="cn-run2">
					<ul id="ul-run2">
					{% for k,key in live_list2 %}
					<li class="box2-2-con">
						<p class="box2-2-con-title">【LIVE】{{ key['keyword'] }}：{{ key['title'] }}</p>
						<div class="box2-2-time">{{ key['time'] }}</div>
						<p class="box2-2-con-ct">{{ key['desc'] }}......</p>
						<div class="box2-2-btn"><a href="{{ key['link'] }}" target="_blank">详细</a></div>
						<hr style="border:1px dotted #666666" />
					</li>
				    {% endfor %}
				    </ul>
				</div></div>

				<div class="box2-2-bg" id="live3" style="display:none"><!-- tag-3 -->
				<div class="gun" id="cn-run3">
					<ul id="ul-run3">
					{% for k,key in live_list3 %}
					<li class="box2-2-con">
						<p class="box2-2-con-title">【LIVE】{{ key['keyword'] }}：{{ key['title'] }}</p>
						<div class="box2-2-time">{{ key['time'] }}</div>
						<p class="box2-2-con-ct">{{ key['desc'] }}......</p>
						<div class="box2-2-btn"><a href="{{ key['link'] }}" target="_blank">详细</a></div>
						<hr style="border:1px dotted #666666" />
					</li>
				    {% endfor %}
				    </ul>
				    </div>
				</div>

			</div>
			<div class="box2-3" id="b3">
				<div class="box2-3-title"><img src="images/box2-ssqx.png"></div>
				<div class="box2-3-tag">
					<div class="box2-tag-hover"><p>8月22号</p></div>
					<div class="box2-tag-normal" style="margin-left: 5px;"><p>8月23号</p></div>
					<div class="box2-tag-normal" style="margin-left: 5px;"><p>8月29-30号</p></div>
				</div>

				<!-- 第一页 -->
				<div class="box2-3-bg" id="contag1">
					<div class="box2-3-t1"><p>[ 8月22日 ]</p></div>
					<div class="box2-3-t2">
						<p>
							到场总人数超
							<font class="font53" id="people">7万</font>
							！！成交金额破
							<font class="font53" id="money">14亿</font>！！
						</p>
						<hr style="border:1px dotted #e00012;width: 90%;" />
					</div>
					<!-- 第一页时间轴 -->

					<div class="box2-3-sjz box2-3-sjz-p1" >
						<div class="sjz-line">
							<div class="sjz-box sjz-box-style1 sjz-box1">
								<div class="info">
									<p>开场仅5分钟</p>
									<p class="fb">第1单</p>
									<i></i>
								</div>
								<div class="time">
									22号 AM 09:05
								</div>
							</div>
							<div class="sjz-box sjz-box-style2 sjz-box2">
								<div class="time">
									22号 AM 10:45
								</div>
								<div class="info">
									<p>入场人数超</p>
									<p class="fb">7万</p>
									<i></i>
								</div>
							</div>
							<div class="sjz-box sjz-box-style3 sjz-box3">
								<div class="info">
									<p>成交金额破</p>
									<p class="fb">1亿</p>
									<i></i>
								</div>
								<div class="time">
									22号 AM 11:20
								</div>
							</div>
							<div class="sjz-box sjz-box-style4 sjz-box4">
								<div class="time">
									22号 PM 14:00
								</div>
								<div class="info">
									<p>成交金额破</p>
									<p class="fb">8亿</p>
									<i></i>
								</div>
							</div>
							<div class="sjz-box sjz-box-style1 sjz-box5">
								<div class="info">
									<p>最高客单值超</p>
									<p class="fb">25万</p>
									<i></i>
								</div>
								<div class="time">
									22号 PM 15:00
								</div>
							</div>
							<div class="sjz-box sjz-box-style2 sjz-box6">
								<div class="time">
									22号 PM 17:10
								</div>
								<div class="info">
									<p>成交金额破</p>
									<p class="fb">14亿</p>
									<i></i>
								</div>
							</div>

						</div>
					</div>
					 <!--
					<div class="box2-3-ppjy">
						<img src="images/box2-ppjy.png">
					</div>
					<div class="box2-3-ppjy-con">
						<img src="images/prd-logo1.jpg">
						<img src="images/prd-logo2.jpg">
						<img src="images/prd-logo3.jpg">
						<img src="images/prd-logo4.jpg">
						<img src="images/prd-logo5.jpg">
					</div>
					-->
					<!-- div class="box2-3-cjl">
						<div style="float:left">
							<img src="images/box2-qx.png">
						</div>
						<div class="box2-3-cjl-con">
							<img src="images/box2-cjl.png" style="float:left"><div class="cjl-num font30 fontred" id="chengjiao">19890302</div>
							<div id="cj_msg">
								<p style="width: 750px;">2015年七夕家装节交易峰值<font class="fontred">223笔/分钟</font>，相比去年家装节<font class="fontred">123笔/分钟</font>，系统支撑能力达到去年<font class="fontred">3倍</font>以上。</p>
							</div>
						</div>
					</div> -->
					<!--
					<div class="box2-3-zshy">
						<img src="images/box2-zshy.png">
					</div>
					
					<div class="box2-3-type">
						<div>
							<div>地板</div>
							<div>瓷砖</div>
							<div>厨电</div>
							<div>衣柜</div>
							<div>橱柜</div>
						</div>
					</div>
					<div class="box2-3-dq">
						<div class="box2-3-dp-up">
							<div><p>1</p><p>福建</p></div>
							<div><p>2</p><p>广东</p></div>
							<div><p>3</p><p>浙江</p></div>
							<div><p>4</p><p>江苏</p></div>
							<div><p>5</p><p>北京</p></div>
						</div>
						<div class="box2-3-dp-down">
							<div><p>6</p><p>湖南</p></div>
							<div><p>7</p><p>山西</p></div>
							<div><p>8</p><p>山东</p></div>
							<div><p>9</p><p>江西</p></div>
							<div><p>10</p><p>贵州</p></div>
						</div>
					</div>
					-->
				</div>

				<!-- 第二页 -->
				<div class="box2-3-bg" id="contag2" style="display:none">
					<div class="box2-3-t1"><p>[ 8月22-23日 ]</p></div>
					<div class="box2-3-t2">
						<p>
							到场总人数超
							<font class="font53" id="people">8万</font>
							！！成交金额破
							<font class="font53" id="money">15亿</font>！！
						</p>
						<hr style="border:1px dotted #e00012;width: 90%;" />
					</div>
					
					 <!-- 第二页时间轴 -->
 					
						<div class="box2-3-sjz box2-3-sjz-p2" >
							<div class="sjz-line">
								<div class="sjz-box sjz-box-style1 sjz-box1">
									<div class="info">
										<p>开场仅5分钟</p>
										<p class="fb">第1单</p>
										<i></i>
									</div>
									<div class="time">
										22号 AM 09:05
									</div>
								</div>
								<div class="sjz-box sjz-box-style2 sjz-box2">
									<div class="time">
										22号 AM 10:45
									</div>
									<div class="info">
										<p>入场人数超</p>
										<p class="fb">7万</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style3 sjz-box3">
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">1亿</p>
										<i></i>
									</div>
									<div class="time">
										22号 AM 11:20
									</div>
								</div>
								<div class="sjz-box sjz-box-style4 sjz-box4">
									<div class="time">
										22号 PM 14:00
									</div>
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">8亿</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style1 sjz-box5">
									<div class="info">
										<p>最高客单值超</p>
										<p class="fb">25万</p>
										<i></i>
									</div>
									<div class="time">
										22号 PM 15:00
									</div>
								</div>
								<div class="sjz-box sjz-box-style2 sjz-box6">
									<div class="time">
										22号 PM 17:10
									</div>
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">14亿</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style3 sjz-box7">
									<div class="info">
										<p>累计入场人数破</p>
										<p class="fb">8万人</p>
										<i></i>
									</div>
									<div class="time">
										23号 AM 10:15
									</div>
								</div>
								<div class="sjz-box sjz-box-style4 sjz-box8">
									<div class="time">
										23号 PM 17:15
									</div>
									<div class="info">
										<p>成交金额超</p>
										<p class="fb">15亿</p>
										<i></i>
									</div>
								</div>
								
								
							</div>
						</div>
 					
					<!--

					<div class="box2-3-ppjy">
						<img src="images/box2-ppjy.png">
					</div>
					<div class="box2-3-ppjy-con">
						<img src="images/prd-logo1.jpg">
						<img src="images/prd-logo2.jpg">
						<img src="images/prd-logo3.jpg">
						<img src="images/prd-logo4.jpg">
						<img src="images/prd-logo5.jpg">
					</div>
					-->
					<!-- 
					<div class="box2-3-cjl">
						<div style="float:left">
							<img src="images/box2-qx.png">
						</div>
						<div class="box2-3-cjl-con">
							<img src="images/box2-cjl.png" style="float:left"><div class="cjl-num font30 fontred" id="chengjiao">19890302</div>
							<div id="cj_msg">
								<p style="width: 750px;">2015年七夕家装节交易峰值<font class="fontred">223笔/分钟</font>，相比去年家装节<font class="fontred">123笔/分钟</font>，系统支撑能力达到去年<font class="fontred">3倍</font>以上。</p>
							</div>
						</div>
					</div>
					 -->
					 <!--
					<div class="box2-3-zshy">
						<img src="images/box2-zshy.png">
					</div>
					<div class="box2-3-type">
						<div>
							<div>地板</div>
							<div>瓷砖</div>
							<div>厨电</div>
							<div>衣柜</div>
							<div>橱柜</div>
						</div>
					</div>
					<div class="box2-3-dq">
						<div class="box2-3-dp-up">
							<div><p>1</p><p>广东</p></div>
							<div><p>2</p><p>福建</p></div>
							<div><p>3</p><p>浙江</p></div>
							<div><p>4</p><p>江苏</p></div>
							<div><p>5</p><p>北京</p></div>
						</div>
						<div class="box2-3-dp-down">
							<div><p>6</p><p>哈尔滨</p></div>
							<div><p>7</p><p>山西</p></div>
							<div><p>8</p><p>山东</p></div>
							<div><p>9</p><p>江西</p></div>
							<div><p>10</p><p>湖南</p></div>
						</div>
					</div>
					-->
				</div>


				<!-- 第三页 -->
				<div class="box2-3-bg" id="contag3" style="display:none">
					<div class="box2-3-t1"><p>[ 8月22-30日 ]</p></div>
					<div class="box2-3-t2">
						<p>
							到场总人数超
							<font class="font53" id="people">10万</font>
							！！成交金额破
							<font class="font53" id="money">19亿</font>！！
						</p>
						<hr style="border:1px dotted #e00012;width: 90%;" />
					</div>
					
							
 					
					<!-- 第三页时间轴 -->
					 <div class="box2-3-sjz box2-3-sjz-p3" >
						<div class="sjz-line">
							<div class="sjz-box sjz-box-style1 sjz-box1">
									<div class="info">
										<p>开场仅5分钟</p>
										<p class="fb">第1单</p>
										<i></i>
									</div>
									<div class="time">
										22号 AM 09:05
									</div>
								</div>
								<div class="sjz-box sjz-box-style2 sjz-box2">
									<div class="time">
										22号 AM 10:45
									</div>
									<div class="info">
										<p>入场人数超</p>
										<p class="fb">7万</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style3 sjz-box3">
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">1亿</p>
										<i></i>
									</div>
									<div class="time">
										22号 AM 11:20
									</div>
								</div>
								<div class="sjz-box sjz-box-style4 sjz-box4">
									<div class="time">
										22号 PM 14:00
									</div>
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">8亿</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style1 sjz-box5">
									<div class="info">
										<p>最高客单值超</p>
										<p class="fb">25万</p>
										<i></i>
									</div>
									<div class="time">
										22号 PM 15:00
									</div>
								</div>
								<div class="sjz-box sjz-box-style2 sjz-box6">
									<div class="time">
										22号 PM 17:10
									</div>
									<div class="info">
										<p>成交金额破</p>
										<p class="fb">14亿</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style3 sjz-box7">
									<div class="info">
										<p>累计入场人数破</p>
										<p class="fb">8万人</p>
										<i></i>
									</div>
									<div class="time">
										23号 AM 10:15
									</div>
								</div>
								<div class="sjz-box sjz-box-style4 sjz-box8">
									<div class="time">
										23号 PM 17:15
									</div>
									<div class="info">
										<p>成交金额超</p>
										<p class="fb">15亿</p>
										<i></i>
									</div>
								</div>
								<div class="sjz-box sjz-box-style1 sjz-box9">
									<div class="info">
										<p>累计入场人数破</p>
										<p class="fb">10万人</p>
										<i></i>
									</div>
									<div class="time">
										29号 AM 10:20
									</div>
								</div>
								<div class="sjz-box sjz-box-style2 sjz-box10">
									<div class="time">
										29号 PM 16:10
									</div>
									<div class="info">
										<p>最高客单值</p>
										<p class="fb">28万</p>
										<i></i>
									</div>
								</div>

								<div class="sjz-box sjz-box-style3 sjz-box11">
									<div class="info">
										<p>成交金额超</p>
										<p class="fb">18.8亿</p>
										<i></i>
									</div>
									<div class="time">
										29号 PM 17:20
									</div>
								</div>
								<div class="sjz-box sjz-box-style4 sjz-box12">
									<div class="time">
										30号 PM 17:30
									</div>
									<div class="info">
										<p>成交金额超</p>
										<p class="fb">19亿元</p>
										<i></i>
									</div>
									
								</div>
							
						</div> 


					</div>
<!--
					<div class="box2-3-ppjy">
						<img src="images/box2-ppjy.png">
					</div>
					<div class="box2-3-ppjy-con">
						<img src="images/prd-logo1.jpg">
						<img src="images/prd-logo2.jpg">
						<img src="images/prd-logo3.jpg">
						<img src="images/prd-logo4.jpg">
						<img src="images/prd-logo5.jpg">
					</div>-->
					<!--<div class="box2-3-cjl">
						<div style="float:left">
							<img src="images/box2-qx.png">
						</div>
						<div class="box2-3-cjl-con">
							<img src="images/box2-cjl.png" style="float:left"><div class="cjl-num font30 fontred" id="chengjiao">19890302</div>
							<div id="cj_msg">
								<p style="width: 750px;">2015年七夕家装节交易峰值<font class="fontred">223笔/分钟</font>，相比去年家装节<font class="fontred">123笔/分钟</font>，系统支撑能力达到去年<font class="fontred">3倍</font>以上。</p>
							</div>
						</div>
					</div>-->
					<!--
					<div class="box2-3-zshy">
						<img src="images/box2-zshy.png">
					</div>
					
					<div class="box2-3-type">
						<div>
							<div>地板</div>
							<div>瓷砖</div>
							<div>厨电</div>
							<div>衣柜</div>
							<div>橱柜</div>
						</div>
					</div>
					<div class="box2-3-dq">
						<div class="box2-3-dp-up">
							<div><p>1</p><p>广东</p></div>
							<div><p>2</p><p>福建</p></div>
							<div><p>3</p><p>浙江</p></div>
							<div><p>4</p><p>江苏</p></div>
							<div><p>5</p><p>北京</p></div>
						</div>
						<div class="box2-3-dp-down">
							<div><p>6</p><p>哈尔滨</p></div>
							<div><p>7</p><p>山西</p></div>
							<div><p>8</p><p>山东</p></div>
							<div><p>9</p><p>江西</p></div>
							<div><p>10</p><p>湖南</p></div>
						</div>
					</div>-->
				</div>


			</div>
		</div>
		<div class="box3" id="b4">
			<div class="box3-con">
				<div class="box3-con-left">
					<div class="left-title"><img src="images/box3-title1.png"></div>
					{% for k,key in news_list %}
					<a href="{{ key['link'] }}" target="_blank">
					<div class="left-con">
						<div class="left-con-1">[{{ key['keyword'] }}] {{ key['title'] }}</div>
						<div class="left-con-2">{{ key['desc'] }}......</div>
						<hr style="border:1px dotted #666666" />
					</div>
					</a>
					{% endfor %}
				</div>
				<div class="box3-con-right">
					<div class="right-title"><img src="images/box3-title2.png"></div>
					<div class="right-con">
						<div class="right-logo"><img src="images/logo.png"></div>
						<div class="right-msg">
							<p>主办单位：腾讯网亚太家居</p>
							<p>举办时间：8月22日-29日</p>
						</div>
						<hr style="border:1px dotted #666666" />
						<div class="right-ts"><font class="jiacu">活动特色：</font>七夕家装节，是中国家居建材行业史无前例的线下团购狂欢盛宴，8月22日-29日首批50个参与城市，30个家居行业领头品牌，让千万业主享受史上最强家装消费优惠</div>
					</div>
				</div>
			</div>
		</div>
		<div class="box4" id="b5">
			<div class="box4-banner-bg">
				<div class="box4-banner">
					<div id="box">
						<ul>
						{% for k,key in jc_list%}
							<li onclick="bigpic(this)"><img src="{{ key['img_url'] }}"/></li>
						{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			<div class="box4-banner-bg2">
				<div>
					<a href="javascript:void(0);" onclick="pic('天津')"><img src="images/city-tianjin.png"></a>
					<a href="javascript:void(0);" onclick="pic('杭州')"><img src="images/city-hangzhou.png"></a>
					<a href="javascript:void(0);" onclick="pic('厦门')"><img src="images/city-xiamen.png"></a>
					<a href="javascript:void(0);" onclick="pic('青岛')"><img src="images/city-qingdao.png"></a>
					<a href="javascript:void(0);" onclick="pic('南昌')"><img src="images/city-nanchang.png"></a>
					<a href="javascript:void(0);" onclick="pic('长沙')"><img src="images/city-changsha.png"></a>
					<a href="javascript:void(0);" onclick="pic('贵阳')"><img src="images/city-guiyang.png"></a>
					<a href="javascript:void(0);" onclick="pic('武汉')"><img src="images/city-wuhan.png"></a>
					<a href="javascript:void(0);" onclick="pic('西安')"><img src="images/city-xian.png"></a>
					<a href="javascript:void(0);" onclick="pic('昆明')"><img src="images/city-kunming.png"></a>
					<a href="javascript:void(0);" onclick="pic('南京')"><img src="images/city-nanjing.png"></a>
					<a href="javascript:void(0);" onclick="pic('哈尔滨')"><img src="images/city-haerbin.png"></a>
					<a href="javascript:void(0);" onclick="pic('济南')"><img src="images/city-jinan.png"></a>
					<a href="javascript:void(0);" onclick="pic('太原')"><img src="images/city-taiyuan.png"></a>
					<a href="javascript:void(0);" onclick="pic('北京')"><img src="images/city-beijing.png"></a>
					<a href="javascript:void(0);" onclick="pic('东莞')"><img src="images/city-dongguang.png"></a>
				</div>
			</div>
			<div class="box4-cyjj-ly" id="b6">
				<div class="box4-cyjj">
					<img src="images/cyjj.png">
				</div>
				<div class="box4-cyjj-logo"><img src="images/alllogo.png"></div>
			</div>
			<div class="box4-bottom"><img src="images/bottom.png"></div>	
		</div>

	<div class="hide" id="navWarp">
		<div class="navWarpInside">
			<p class="z5"><img src="images/icon5.png"/><a href="javascript:void(0);">活动直播</a></p>
			<p class="z4"><img src="images/icon5.png"/><a href="javascript:void(0);">数说七夕家装节</a></p>
			<p class="z3"><img src="images/icon5.png"/><a href="javascript:void(0);">最新快讯</a></p>
			<p class="z2"><img src="images/icon5.png"/><a href="javascript:void(0);">精彩图集</a></p>
			<p class="z1"><img src="images/icon5.png"/><a href="javascript:void(0);">家居大牌</a></p>
			<p class="strong"><a href="javascript:void(0);">TOP</a></p>
		</div>
	</div>

	<div id="bg"></div>
	<div class="tan" id="tan">
		<div class="tan-close">
			<a href="javascript:void(0);" id="close"><img src="images/icon2.png"></a>
		</div>
		<div class="tan-con" id="imgurl">
		</div>
		<div class="tan-left">
			<a href="javascript:void(0);" onclick="qie('left')"><img src="images/icon3.png"></a>
		</div>
		<div class="tan-right">
			<a href="javascript:void(0);" onclick="qie('right')"><img src="images/icon4.png"></a>
		</div>

	</div>
	<input type="hidden" />
	<div class="tan" id="tan2">
		<div class="tan-close">
			<a href="javascript:void(0);" id="close2"><img src="images/icon2.png"></a>
		</div>
		<div class="tan-con2">
			<img src="" id="tan2_img" >
		</div>
	</div>
  
	<script src="/qxzj/js/jquery-1.7.2.min.js" type="text/javascript"></script>
	<script src="/qxzj/js/move.js" type="text/javascript"></script>
	<script src="/qxzj/js/MSClass.js" type="text/javascript"></script>
	<script type="text/javascript" src="/qxzj/js/my.js?vid=1.3"></script>
    <?php $this->partial("public/zt_head")?>
    <?php $this->partial("public/zt_footer")?>
 </body>
</html>
