
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope">
				<h1 class="m-n font-thin h3">
				<a href="/admin/group/index">优品团 ></a> <a href="/admin/group/city_index">城市管理 ></a> {% if data['id'] !='' %}编辑{% else %}添加{% endif %}城市</h1>
			</div>
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<form class="panel-body form-horizontal" role="form" method="post" enctype="multipart/form-data">
						<div class="form-group form-group-sm">
							<label for="active_quantity" class="col-sm-1 control-label">城市名称:</label>
							<div class="col-xs-2"><input class="form-control" type="text"  name="city_name" value="{{ data['city_name'] }}" ></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="goods_quantity" class="col-sm-1 control-label">城市代号:</label>
							<div class="col-xs-2"><input class="form-control" type="text"  name="city_code" value="{{ data['city_code'] }}" ></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="discount" class="col-sm-1 control-label">经度（x）:</label>
							<div class="col-xs-2"><input class="form-control" type="text"  name="lng" value="{{ data['lng'] }}" ></div>经度坐标（0~180）例如北京的经度为：116.490259  <font color="red">错误的坐标会导致定位不准确，请认真填写</font>
						</div>
						<div class="form-group form-group-sm">
							<label for="range_min" class="col-sm-1 control-label">纬度（y）:</label>
							<div class="col-xs-2"><input class="form-control" type="text"  name="lat" value="{{ data['lat'] }}" /></div>纬度坐标（0~90）例如北京的纬度为：39.878315
						</div>
						<div class="form-group form-group-sm">
						    <label for="range_min" class="col-sm-1 control-label"></label>
							<a href="http://api.map.baidu.com/lbsapi/getpoint/index.html" target="_blank">点击进入-拾取坐标系统</a>
						</div>
						<div class="form-group" style="margin-bottom:0px;">
							<label class="col-sm-1 control-label"></label>
							<div class="col-xs-8">
							    <input type="hidden" name="id" value="{{ data['id'] }}">
								<button type="submit" class="btn btn-primary btn-sm">确定</button>
								<a class="btn btn-default btn-sm" style="margin-left:10px;" href="/admin/group/city_index" role="button">返回</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("index/footer")?>