
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope">
				<h1 class="m-n font-thin h3">
				<a href="/admin/group/index">优品团 ></a> <a href="/admin/group/class_list">商品分类管理 ></a> {% if data['id'] != '' %}编辑{%  else %}添加{% endif %}分类</h1>
			</div>
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<form class="panel-body form-horizontal" role="form" method="post" enctype="multipart/form-data">
						<div class="form-group form-group-sm">
							<label for="active_quantity" class="col-sm-1 control-label">分类名称:</label>
							<div class="col-xs-2"><input class="form-control" type="text"  name="class_name" value="{{ data['class_name'] }}" ></div>
						</div>

						<div class="form-group" style="margin-bottom:0px;">
							<label class="col-sm-1 control-label"></label>
							<div class="col-xs-8">
							    <input type="hidden" name="id" value="{{ data['id'] }}">
								<button type="submit" class="btn btn-primary btn-sm">确定</button>
								<a class="btn btn-default btn-sm" style="margin-left:10px;" href="/admin/group/class_list" role="button">返回</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("index/footer")?>