
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<script type="text/javascript" src="/common/js/kindeditor/kindeditor.js"></script>
<script type="text/javascript" src="/common/js/kindeditor/lang/zh_CN.js"></script>
<script type="text/javascript" src="/common/js/kindeditor/plugins/code/prettify.js"></script>
<script type="text/javascript" src="/common/js/kindeditor/plugins/autoheight/autoheight.js"></script>
<script type="text/javascript" src="/common/js/My97DatePicker/WdatePicker.js"></script>
<link rel="stylesheet" href="/common/js/kindeditor/themes/default/default.css"/>
<script>
var editor;
KindEditor.ready(function(K) {
editor = K.create('#desc', {
resizeType : 1,
allowPreviewEmoticons : false,
allowImageUpload : true,
allowFileManager : true,
autoHeightMode : true,
afterBlur: function(){this.sync();},
items : [
'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
'superscript', 'clearhtml', 'quickformat', 'selectall','formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
'anchor', 'link', 'unlink', 'fullscreen']
});
});
</script>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope">
				<h1 class="m-n font-thin h3"><a href="/admin/group/index">优品团 ></a> <a href="/admin/group/discount_list">优惠信息管理 ></a> {% if data['id'] != '' %}编辑{% else %}添加{% endif %}优惠信息</h1>
			</div>
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<form class="panel-body form-horizontal" role="form" method="post" enctype="multipart/form-data">
						<div class="form-group form-group-sm">
							<label for="goods_category" class="col-sm-1 control-label">关键词:</label>
							<div class="col-xs-2"><input class="form-control" type="text" name="keyword" value="{{ data['keyword'] }}" ><font color="red">关键词不得超过2个字</font></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="desc" class="col-sm-1 control-label">优惠简述:</label>
							<div class="col-xs-7"><textarea class="form-control" name="info">{{ data['info'] }}</textarea></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="desc" class="col-sm-1 control-label">优惠详情:</label>
							<div class="col-xs-7"><textarea class="form-control" id="desc" name="details">{{ data['details'] }}</textarea></div>
						</div>
						<div class="form-group" style="margin-bottom:0px;">
							<label class="col-sm-1 control-label"></label>
							<div class="col-xs-8">
							    <input type="hidden" name="id" value="{{ data['id'] }}">
								<button type="submit" class="btn btn-primary btn-sm">确定</button>
								<a class="btn btn-default btn-sm" style="margin-left:10px;" href="/admin/group/discount_list" role="button">返回</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->partial("index/footer")?>