
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope"><h1 class="m-n font-thin h3">统计</h1></div>
			
			<div class="wrapper-md ng-scope form-inline" style="padding:10px 20px 0px 20px;">
				<a class="btn btn-default btn-sm" href="/admin/seckill/statistics/{{actionId}}/1" role="button">分享汇总</a>
				<a class="btn btn-default btn-sm" href="/admin/seckill/statistics/{{actionId}}/2" role="button">每日汇总</a>
				<a class="btn btn-default btn-sm pull-right" href="/admin/seckill/index" role="button">返回</a>
			</div>
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
				{% if type == 1 %}
					<table class="table table-hover m-b-none">
						<thead>
							<tr>
								<th>用户id</th>
								<th>微信名</th>
								<th>微信id</th>
								<th>分享数</th>
								<th>分享点击数</th>
							</tr>
						</thead>
						<tbody>
					{% for k,v in userlist %}
							<tr class="odd">
								<td>{{ v['user_id'] }}</td>
								<td>{{ v['wx_name'] }}</td>
								<td>{{ v['wx_id'] }}</td>
								<td>{{ v['num'] }}</td>
								<td>{{ clicklist[v['user_id']]['num'] }}</td>
							</tr>
					{% endfor %}
						</tbody>
					</table>
				{% elseif type == 2 %}
					<table class="table table-hover m-b-none">
						<thead>
							<tr>
								<th>日期</th>
								<th>秒杀数</th>
								<th>分享数</th>
								<th>朋友圈点击数</th>
								<th>微信群点击数</th>
							</tr>
						</thead>
						<tbody>
					{% for k,v in data %}
							<tr class="odd">
								<td>{{ k }}</td>
								<td>{{ v['miao'] }}</td>
								<td>{{ v['share'] }}</td>
								<td>{{ v['groupmessage'] }}</td>
								<td>{{ v['timeline'] }}</td>
							</tr>
					{% endfor %}
						</tbody>
					</table>
				{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->partial("index/footer")?>

<script type="text/javascript">



</script>