<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> 雅兰床垫工厂店团购会</title>
<meta name="keywords" content=" 雅兰床垫工厂店团购会" />
<meta name="description" content=" 雅兰床垫工厂店团购会" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/yalan/css/com.css?v=1.4" />
<script type="text/javascript">
var payDomain = '{{payDomain}}';
</script>
</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>
<div class="wraper">
    <div class="swiper-container swiper-pages" id="swiper-container1">
        <div class="swiper-wrapper" id="wrapper">
			<!-- 首页 -->
			<div class="swiper-slide page-1 ps1">
				<div class="container">
					<div class="am am2">
						<img src="/yalan/images/p0_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="1">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 仅此一天5折 -->
			<div class="swiper-slide page-2 ps2">
				<div class="container">
					<div class="am am1">
						<img src="/yalan/images/p1_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="2">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 1元砍价 -->
			<div class="swiper-slide page-3 ps2">
				<div class="container">
					<div class="am am1">
						<img src="/yalan/images/p2_1.png"  />
					</div>
					<!-- <div class="am swiper2">
						<div id="swiper2" class="swiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">

									<div class="swiper-slide">
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/1.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/2.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/3.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/4.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
									</div>
									<div class="swiper-slide">
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/5.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/6.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/7.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/8.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
									</div>
									<div class="swiper-slide">
										<div class="imgBox">
											<img src="/meilige/images/yiyuanqiang/default_yiyuanqiang.png" data-src="/meilige/images/yiyuanqiang/9.jpg"  />
											<div class="price">￥<span>1</span></div>
										</div>
									</div>
								</div>
							</div>

							<div class="pagination"></div>
						</div>
					</div>	 -->
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="3">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 5折限量抢购 -->
			<div class="swiper-slide page-4 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p3_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="4">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 单单有送 -->
			<div class="swiper-slide page-5 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p4_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="5">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 免单 -->
			<div class="swiper-slide page-6 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p5_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="6">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 新增 -->
<!-- 			<div class="swiper-slide ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/new1_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am bmOpen">
				 		<div class="click_btn" data-id="new1" >

				 		</div>
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div> -->
			<div class="swiper-slide page-7 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p6_2.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="7">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 到场有礼 -->
			<div class="swiper-slide page-8 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p6_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="8">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 砸金蛋 -->
			<!-- <div class="swiper-slide page-8 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p8_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am bmOpen">
				 		<div class="click_btn" data-id="8" >

				 		</div>
						<p >主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div> -->
			<!-- 服务 -->
			<div class="swiper-slide page-9 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p7_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="9">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 质量保障 -->
			<div class="swiper-slide page-10 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p8_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="10">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 床垫十大品牌 -->
			<div class="swiper-slide page-11 ps2">
				<div class="container">
					<div class="am am1">
						<img data-src="/yalan/images/p9_1.png"  />
					</div>
					<div class="am logo">
						<img src="/yalan/images/logo.png"  />
					</div>
					<div class="am click_btn" data-id="11">
						<img src="/yalan/images/lp.png" alt="">
				 	</div>
				 	<div class="am bmOpen">
						<p class="p2">主办方：优居网 雅蘭</p>
					</div>
				</div>
			</div>
			<!-- 地址 -->

       </div>
		<div class="pagination" id="pagination1"></div>
    </div>
    <!-- 下滑提示 -->
    <div class="cn-slidetips next">
  	    <div class="slidetips">
  	        <a href="javascript:void(0);" title="NEXT" id="next">
  	            <img src="/yalan/images/next.png" />
  	        </a>
  	    </div>
  	</div>

	<!-- 报名页 -->
	<div class="baoming hide" id="baoming">
		<div class="bmWarp">
			<span class="bmClose">×</span>
			<!-- 领票 -->
			<div class="lpForm">
				<p class="bmHead">
					雅蘭团购会0元领票
				</p>
			    <p class="bmmsg">已有<span class="bmnum">{{ count }}</span>人成功领取！</p>
				<p><input type="text" name="name" class="name" placeholder="请填写姓名" /></p>
				<p><input type="number" name="tel" class="tel" placeholder="请填写手机号码" /></p>
				<p class="atten">* 此号码仅用于本次报名使用</p>
				<p class="lpBtn false">立即领票</p>
			</div>
			<!-- 提交验证 -->
			<div class="bmForm hide">
				<p class="bmHead">
					雅蘭团购会0元领票
				</p>
				<p class="bmmsg">请完善您的收货地址，我们会为您寄送门票</p>
				<p><select id="area" class="area"></select></p>
				<p><input type="text" id="address" name="address" class="address" placeholder="请填写详细地址" /></p>
				<p class="mtBig"><input type="number" name="code" class="code" placeholder="请输入验证码" /><span class="getCode">获取验证码</span></p>
				<input type="hidden" id="send_phone" value=""/>
				<input type="hidden" id="btn_id" value=""/>
				<input type="hidden" id="verify" value=""/>
				<p class="tips"></p>
				<p class="bmBtn false">提交验证</p>
			</div>
		</div>
	</div>

	<!-- 报名成功页 -->
	<div class="succeed hide" id="succeed">
		<div class="logo">
			<img src="/yalan/images/logo.png"  />
		</div>
		<div class="succeedText1">
			恭喜您报名成功
		</div>
		<div class="succeedText2">
			<p>我们将于24小时内电联确认您的地址信息，</p>
			<p>请注意接听！</p>
		</div>
		<a class="succeedAd" href="/phone/yiyuanqiang/index/11">
			<img src="/yalan/images/ylSucceed.jpg"  />
		</a>

	</div>

	<!-- 重复报名 -->
	<div class="succeed hide" id="again">
		<div class="logo">
			<img src="/yalan/images/logo.png"  />
		</div>
		<div class="succeedText3">
			您已成功报名过，请勿重复报名!
		</div>
		<a class="succeedAd" href="/phone/yiyuanqiang/index/11">
			<img src="/yalan/images/ylSucceed.jpg"  />
		</a>

	</div>

</div>

<script src="/common/js/zepto.min.js"></script>
<script src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script src="/yalan/js/my.js?v=1.4"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>

<script>
	//微信分享控制
	wx.config({
	      debug: false,
	      appId: '<?php echo $signPackage["appId"];?>',
		  timestamp: '<?php echo $signPackage["timestamp"];?>',
		  nonceStr: '<?php echo $signPackage["nonceStr"];?>',
	      signature: '<?php echo $signPackage["signature"];?>',
	      jsApiList: [
            'checkJsApi',
	        'onMenuShareTimeline',
	        'onMenuShareAppMessage',
	        'onMenuShareQQ',
	        'onMenuShareWeibo'
	      ]
	  });
	wx.ready(function () {
		var wxData = {
			"imgUrl":'{{domain}}/yalan/images/share.jpg',
			"link":'{{domain}}/phone/yalan/index',
			"desc":"11月21日雅蘭集团—工厂直供团购会，大家都知道0元领票戳这里！",
			"title":"11月21日雅蘭集团—工厂直供团购会，大家都知道0元领票戳这里！"
		};
		wx.onMenuShareAppMessage(wxData);
		wx.onMenuShareTimeline(wxData);
	});
</script>
</body>
</html>