
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<style type="text/css">
	.img-list{display:inline-flex;}
	.img-list .img-row{margin-right:10px;}
	.img-list .img-row:last-child{margin-right:0px;}
	
	.img-row{position:relative;}
	.img-row .inimg{display:inherit;border:1px solid #cfdadd;}
	.img-row img.inimg{width:195px;height:100px;background-color:#fff;border:none;}
	.img-row .inimg.img-btn{position:absolute;opacity:0;z-index:100;top:0px;left:0px;width:195px;height:100px;cursor:pointer;}
	.img-row .inimg.img-url{width:195px;}
	.img-row .inimg.img-url{width:195px;}
	.img-row .inimg.isshow{width:195px;}
	.img-row .inimg.img-close{
		display:block;width:15px;height:15px;left:-5px;top:-5px;cursor:pointer;z-index:200;
		position:absolute;border:none;background:url(/admin/images/close.jpg) no-repeat;
	}
	
</style>

<script type="text/javascript" src="/common/js/My97DatePicker/WdatePicker.js"></script>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope">
				<h1 class="m-n font-thin h3">编辑活动</h1>
			</div>
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<form class="panel-body form-horizontal" role="form" method="post" enctype="multipart/form-data">
						<div class="form-group form-group-sm">
							<label for="zhan_name" class="col-sm-1 control-label">活动名称:</label>
							<div class="col-xs-2"><input class="form-control" type="text" name="zhan_name" value="{{data['zhan_name']}}" maxlength="16"/></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="starttime" class="col-sm-1 control-label">开始时间:</label>
							<div class="col-xs-2">
								<input class="form-control" type="text" name="starttime" value="{{date('Y-m-d', strtotime(data['starttime']))}}" onFocus="WdatePicker({dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})" />
							</div>
						</div>
						<div class="form-group form-group-sm">
							<label for="endtime" class="col-sm-1 control-label">结束时间:</label>
							<div class="col-xs-2">
								<input class="form-control" type="text" name="endtime" value="{{date('Y-m-d', strtotime(data['endtime']))}}" onFocus="WdatePicker({dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})" />
							</div>
						</div>
						<div class="form-group form-group-sm">
							<label for="show" class="col-sm-1 control-label">活动类型:</label>
							<div class="col-xs-2 form-inline">
								<select class="input-sm form-control w-sm inline v-middle" name="act_type" id="act_type">
			                      <option value="综合建材" {% if data['act_type'] == '综合建材' %}selected{% endif %}>综合建材</option>
			                      <option value="单品牌" {% if data['act_type'] == '单品牌' %}selected{% endif %}>单品牌</option>
			                    </select>
							</div>
						</div>
						<div class="form-group form-group-sm">
							<label for="zhan_name" class="col-sm-1 control-label">排序:</label>
							<div class="col-xs-2"><input class="form-control" type="text" name="sort" maxlength="16"  value="{{ data['sort'] }}"/></div>
						</div>
						<div class="form-group form-group-sm">
							<label for="show" class="col-sm-1 control-label">是否显示:</label>
							<div class="col-xs-2 form-inline">
								<input type="checkbox" name="show" value='1' {% if data['show'] == 1 %} checked {% endif %} />
							</div>
						</div>
						<div class="form-group form-group-sm">
							<label for="logo1" class="col-sm-1 control-label">默认logo:</label>
							<div class="col-xs-2 img-list">
								<div class="img-row" data-sort="bg">
									<span class='inimg img-close'></span>
									<img {% if data['logo1'] %}src="/uploads/zhan/{{data['logo1']}}"{% endif %} class="inimg" />
									<input type="file" name='logo1' class="inimg img-btn" />
								</div>
							</div>
						</div>
						<div class="form-group form-group-sm">
							<label for="logo2" class="col-sm-1 control-label">替换logo:</label>
							<div class="col-xs-2 img-list">
								<div class="img-row" data-sort="bg">
									<span class='inimg img-close'></span>
									<img {% if data['logo2'] %}src="/uploads/zhan/{{data['logo2']}}"{% endif %} class="inimg" />
									<input type="file" name='logo2' class="inimg img-btn" />
								</div>
							</div>
						</div>
						<div class="form-group" style="margin-bottom:0px;">
							<label class="col-sm-1 control-label"></label>
							<div class="col-xs-8">
								<button type="submit" class="btn btn-primary btn-sm">确定</button>
								<a class="btn btn-default btn-sm" style="margin-left:10px;" href="/admin/zhan/action/list" role="button">返回</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->partial("index/footer")?>

<script type="text/javascript">

$(document).on("change",".img-row .img-btn",function(){
	var url = "";
	if (window.createObjectURL != undefined) {
		url = window.createObjectURL(this.files[0])
	} else if (window.URL != undefined) {  // IE
		url = window.URL.createObjectURL(this.files[0])
	} else if (window.webkitURL != undefined) {
		url = window.webkitURL.createObjectURL(this.files[0])
	}
	$(this).parent().find("img.inimg").attr('src',url);
});

//删除图片
$(document).on("click",".img-row .img-close",function(){
	var obj = $(this).parent();
	var name = obj.find("input[type='file']").attr('name');
	if(parseInt(imgId) > 0){
		$.ajax({
			async:true,
			url:"/admin/zhan/logodel/logodel/{{data['zhan_id']}}/"+name,
			type:"get",
			dataType:"json",
			success:function(result){
				if(result.code == 1){
					obj.find("img.inimg").attr('src','');
					obj.find("input[type='file']").remove();
					obj.append("<input type='file' name='"+name+"' class='inimg img-btn' />");
				}else{
					alert(result.msg);
				}
			}
		});
	}else{
		obj.remove();
	}
});

$(document).ready(function() {
	
	
});

</script>