<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope">
  <div class="app-content-body fade-in-up ng-scope" >
   <div class="ng-scope">
    <div class="bg-light lter b-b wrapper-md ng-scope">
        <h1 class="m-n font-thin h3">【{{ act_name }}】-报名数据统计</h1>
    </div>
    
    <div class="wrapper-md ng-scope">
    <?php $this->partial("zhan/navigation")?>
           <!-- tips -->
        <div class="alert ng-isolate-scope alert-info alert-dismissable">
        <div ng-transclude=""><span class="ng-binding ng-scope">报名转化率 = ”报名按钮“的报名数 / ”报名按钮“的点击数</span></div>
        </div>
        <!--/ tips -->
        <div class="panel panel-default">
        <div class="table-responsive">
          <div class="panel panel-default">
            <div class="panel-heading">统计</div>
            <table class="table table-striped m-b-none">
              <tbody>
                <tr>                    
                  <td>“报名按钮”总点击数</td>
                  <td class="text-danger" style="width:70px;">
                    <i class="fa"></i> {{ click_num }}
                  </td>
                </tr>
                <tr>                    
                  <td>总报名数</td>
                  <td class="text-danger" style="width:70px;">
                    <i class="fa"></i> {{ bm_count }}
                  </td>
                </tr>
                <tr>                    
                  <td>总转化率</td>
                  <td class="text-danger" style="width:70px;">
                    <i class="fa"></i> {{ total_zhl }}%
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
       <div class="row">
          <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <span class="label bg-info pull-right m-t-xs">{{ city_num }} 个城市站</span>
                                       各城市站“报名按钮”点击量排行情况
            </div>
            <table class="table table-striped m-b-none">
              <thead>
                <tr>
                  <th>城市站</th>
                  <th style="width:50%"></th>
                  <th>占比</th>
                  <th>点击数</th>
                </tr>
              </thead>
              <tbody>
              {% for k in city_sort %}
                <tr>
                  <td>{% if k['city'] == '' %}ID为{{ k['c_id'] }}的分站已删除{% else %}{{ k['city'] }}{% endif %}</td>
                  <td>
                    <div class="progress progress-sm progress-striped active m-t-xs m-b-none">
                      <div class="progress-bar {{ k['color'] }}" data-toggle="tooltip" data-original-title="{{ k['proportion'] }}%" style="width: {{ k['proportion'] }}%"></div>
                    </div>
                  </td>
                  <td>{{ k['proportion'] }}%</td>
                  <td>{{ k['click_num'] }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <span class="label bg-info pull-right m-t-xs">{{ btn_num }} 个布点位置</span>
                                       各屏“报名按钮”点击量排行情况
            </div>
            <table class="table table-striped m-b-none">
              <thead>
                <tr>
                  <th>布点位置</th>
                  <th style="width:30%"></th>
                  <th>占比</th>
                  <th>点击数</th>
                  <th>报名转化率</th>
                </tr>
              </thead>
              <tbody>
              {% for k in array_sort %}
                <tr>
                  <td>{{ k['name'] }}</td>
                  <td>
                    <div class="progress progress-sm progress-striped active m-t-xs m-b-none">
                      <div class="progress-bar {{ k['color'] }}" data-toggle="tooltip" data-original-title="{{ k['proportion'] }}%" style="width: {{ k['proportion'] }}%"></div>
                    </div>
                  </td>
                  <td>{{ k['proportion'] }}%</td>
                  <td>{{ k['click_num'] }}</td>
                  <td>{{ k['bm_num'] }}/{{ k['click_num'] }} = {{ k['zhl'] }}%</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<?php $this->partial("index/footer")?>