<div class="m-b-sm">
<div class="btn-group" ng-init="radioModel = 'Male'">
  <a href="/admin/zhan/register_list/{{ act_id }}"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>用户报名数据表</label></a>
  <a href="/admin/zhan/city_ranking/{{ act_id }}"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>城市排行</label></a>
  <a href="/admin/zhan/budian_statistics/{{ act_id }}"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>页面布点数据统计</label></a>
</div>
</div>