<!DOCTYPE html>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<meta name="viewport" content=" initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="format-detection" content="telephone=no">
        <title>VIP激活卡</title>
		<link rel="stylesheet" href="/activecode/css/com.css?v=2.1" type="text/css"/>
		<script type="text/javascript" src="/common/js/zepto.min.js"></script>
		<script src="/common/js/tongji.js"></script>
    </head>
	<body>
		<div class="form-box">
			<div class="form-title">
				<img src="/activecode/images/title.png?v=1.0" >
			</div>
			<div class="text-box">
				<div class="ftext fname"><i></i>  |  <input type="text" name="name"  id="name" value="" placeholder="姓名" maxlength="10"></div>
				<div class="ftext fphone"><i></i>  |  <input type="text" name="phone"  id="phone" value="" placeholder="电话" maxlength="11"></div>
				<div class="ftext fcard"><i></i>  |  <input type="text" name="card"  id="card" value="" placeholder="请输入VIP卡的ID" maxlength="10"></div>
				<div class="ftext fcaptcha" style="border-bottom: 1px solid #b82424;"><i></i>  |  <input type="text" name="captcha"  id="captcha" value="" placeholder="请输入VIP卡的验证码" maxlength="5"></div>
			</div>
			<div class="form-submit">
				<img src="/activecode/images/submit-btn.png?v=1.0" >
			</div>
			<div class="copyright">
				<img src="/activecode/images/copyright.png?v=1.0" >
			</div>
		</div>
		<div class="money-page hide">
			<div class="money-title">
				<img src="/activecode/images/money-title.png?v=1.0" >
			</div>
			<div class="money-bag">
				<img src="/activecode/images/money-bag.png?v=1.0" >
				<div class="money-btn">
					<a href="/phone/hongbao/index2?from=vipcode"><img src="/activecode/images/money-btn.png?v=1.0" ></a>
				</div>
			</div>
			
			<div class="copyright">
				<img src="/activecode/images/copyright.png?v=1.0" >
			</div>
		</div>
		<script src="/common/js/zepto.min.js"></script>
		<script src="/activecode/js/my.js?v=1.0"></script>
	</body>
</html>