<!-- <div class="m-b-sm">
    <div class="btn-group btn-group-justified">
      <a href="/admin/qixi/index" class="btn btn-primary">报名数据表</a>
      <a href="/admin/qixi/baoming_statistics" class="btn btn-info">报名数据统计</a>
      <a href="/admin/qixi/budian" class="btn btn-success">布点数据表</a>
      <a href="/admin/qixi/budian_statistics" class="btn btn-danger">布点数据统计</a>
    </div>
</div> -->

<div class="m-b-sm">
<div class="btn-group" ng-init="radioModel = 'Male'">
  <a href="/admin/qixi/index"><label class="btn btn-sm btn-info ng-untouched ng-valid ng-dirty"><i class="fa fa-check text-active"></i>报名数据表</label></a>
  <a href="/admin/qixi/baoming_statistics"><label class="btn btn-sm btn-success ng-untouched ng-valid ng-dirty"><i class="fa fa-check text-active"></i>报名数据统计</label></a>
  <a href="/admin/qixi/budian"><label class="btn btn-sm btn-primary ng-untouched ng-valid ng-dirty"><i class="fa fa-check text-active"></i>布点数据表</label></a>
  <a href="/admin/qixi/budian_statistics"><label class="btn btn-sm btn-danger ng-untouched ng-valid ng-dirty"><i class="fa fa-check text-active"></i>布点数据统计</label></a>
</div>
</div>