
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope"><h1 class="m-n font-thin h3">报名列表</h1></div>
			
			<div class="wrapper-md ng-scope form-inline" style="padding:10px 20px 0px 20px;">
				<input type="text" class="form-control input-sm" id="phone" placeholder="手机号">
				<input type="text" class="form-control input-sm" id="userName" placeholder="用户名" style="width:60px;">
				<input type="text" class="form-control input-sm" id="userId" placeholder="用户ID" style="width:60px;">
				<a class="btn btn-default btn-sm" href="javascript:searchGoods()" role="button">查找</a>
				<a class="btn btn-default btn-sm pull-right" href="/admin/yizhangou/action/list/{{groupId}}" role="button">返回</a>
				<a class="btn btn-default btn-sm pull-right" href="/admin/yizhangou/export/{{actionId}}" role="button">导出</a>
			</div>
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<div class="table-responsive">
						<table id="userList" data-toggle="table"></table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->partial("index/footer")?>

<script type="text/javascript">

function pan(m){
	if(m == 1){
		return '是';
	}else{
		return '否';
	}
}

var table = $("#userList").bootstrapTable({
	method: 'get',
	url: '/admin/yizhangou/baoming/{{actionId}}/1',
	classes:"table table-hover table-condensed m-b-none",
	striped: false,
	sidePagination:'server',
	pagination: true,
	pageSize: 10,
	pageList: [5, 10, 20],
	showColumns:false,
	//clickToSelect: true,
	columns: [
		{ field: 'id',title: 'ID',align: 'center',valign: 'middle',sortable: true },
		{ field:'user_id', title:'用户id', align:'center', valign:'middle' },
		{ field:'user_name', title:'用户名', align:'center', valign:'middle' },
		{ field:'phone', title:'手机号', align:'center', valign:'middle' },
		{ field:'auth', title:'是否验证', align:'center', valign:'middle',formatter:pan },
		{ field:'from', title:'来源', align:'center', valign:'middle' },
		{ field:'ispiao', title:'领票', align:'center', valign:'middle',formatter:pan },
		{ field:'isquan', title:'领卷', align:'center', valign:'middle',formatter:pan },
		//{ field:'fanye', title:'翻页', align:'center', valign:'middle',formatter:pan },
		//{ field:'vcard', title:'v卡', align:'center', valign:'middle',formatter:pan },
		{ field:'ip', title:'ip', align:'center', valign:'middle' },
		{ field:'address', title:'地址', align:'center', valign:'middle' },
		{ field:'time', title:'报名时间', align:'center', valign:'middle' },
	],
	queryParams: function(params){
		var phone = $("#phone").val();
		var userName = $("#userName").val();
		var userId = $("#userId").val();
		return {phone:phone, userName:userName, userId:userId, sort:params.sort, order:params.order, limit:params.limit, offset:params.offset};
	}
});


function searchGoods(){
	var phone = $("#phone").val();
	var userName = $("#userName").val();
	var userId = $("#userId").val();
	table.bootstrapTable('refresh', {query:{phone:phone, userName:userName, userId:userId}});
}



</script>