
<html><!--
本游戏版权归天津九章科技有限公司所有，请遵守规则，欢迎转发。
1.你可以收集、分享、转发本游戏。
2.你可以在自己的服务器上存储本游戏。
3.你可以修改游戏涉及的所有js代码。
4.你可以修改更多游戏APP_LIST_URL的指向。
5.你可以修改本html文件，但需保留本声明。
6.你不可以修改游戏加载屏的内容。
7.你不可以修改羊驼关注页面的指向。
8.你不可以在游戏外遮盖游戏加载屏，和求关注的羊驼图标。
9.本公司保留本游戏所有权利。如果你有其他要求，请联系QQ 1563344353。
--><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<title>扯红包</title>
<script type="text/javascript">
var GID = "shuqian";
var SCORE_LIMIT = 6000;
var APP_LIST_URL = '';
var APP_FOLLOW_URL = '';
</script>
<script type="text/javascript" src="/rpgame/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/rpgame/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/rpgame/js/createjs-2013.12.12.min.js"></script>
<script type="text/javascript" src="/rpgame/js/qipa_app.js"></script>
<script type="text/javascript" src="/rpgame/js/qipa_stage.js"></script>
<script type="text/javascript" src="/rpgame/js/main.js"></script>
<script language="javascript">

// var sumScore = {{ agentScore }}; //打开页面时后台回传当前总成绩
var first_tag = false;

function dp_submitScore(score){
	if(!first_tag){
		first_tag = true;
	}else{
		$.ajax({
	        async:false,
	        url:'../../phone/rpgame/submitscore',
	        data:{score:score},
	        type: "post",
	        dataType:'json',
	        success:function(result){
	     		console.log(result.errcode);
	            //数据返回后执行
	            if(result.errcode != 0){
	                alert(result.errmsg);
	                return false;
	            }else{
	            	myData.score = score;
	        		console.log(myData.score);
// 	        		sumScore += score;
	        		$("#result .result_score").html(score);
	        		$("#result .result_all_score").html(result.score+score);
	        		$("#result").show();
	            }
	        }
	    });
	}
}
function checkCardId(){
	var id = $("#cardID").val();
	var tag = false;
	//console.log(id);
	if(!id){
		alert("请输入卡号ID");
		return false;
	}else{
		//后台验证
		$.ajax({
		        async:false,
		        url:'../../phone/rpgame/checkid',
		        data:{card:id},
		        type: "post",
		        dataType:'json',
		        success:function(result){
		            //数据返回后执行
		            if(result.errcode != 0){
		                alert(result.errmsg);
		                return false;
		            }else{
		            	tag = true;
		            }
		            
		        }
		    });
	}

	if(tag){ 
		return true;
	}else{
		return false;
	}
}
function djs(){
	$("#djs").show();
	var i = 2;
	var time = setInterval(function(){
		if(i>0){
			$("#djs img").hide();
			$("#djs .djs"+i).show();
			i--;
		}else{
			$("#djs").hide();
			clearInterval(time);
		}
	},1000);
}



$(function(){
	/*首次登陆*/
	$("#submitinfo").click(function(){
		var city = $("#city").val();
		var name = $("#name").val();
		if(city == "您所在的城市"){
			alert("请选择城市");
			return;
		}else if(name == ""){
			alert("请填写姓名");
			return;
		}else{
			$.ajax({
		        async:false,
		        url:'../../phone/rpgame/submitinfo',
		        data:{name:name,city:city},
		        type: "post",
		        dataType:'json',
		        success:function(result){
		            //数据返回后执行
		            if(result.errcode != 0){
		                alert(result.errmsg);
		                return false;
		            }else{
		                alert(result.errmsg);
		                $("#my .name").empty();
		                $("#my .name").html(result.name);
		                $("#my .score").empty();
		                $("#my .score").html("目前积分：0");
		                $("#rank .youRank .city").html(result.city);
		            	$("#frist").hide();
		            	$("#index").show();
		                return false;
		            }
		            
		        }
		    });
		
		}
	});
	
	/*打开排行榜*/
	
	$(".rankBtn").click(function(){
		console.log("rank")
		var i;
		var list = $("#rank .rankList");
		list.empty();
		$.ajax({
	        async:false,
	        url:'../../phone/rpgame/rank',
	        type: "post",
	        dataType:'json',
	        success:function(result){
	            //数据返回后执行
	            if(result.errcode != 0){
	                alert(result.errmsg);
	                return false;
	            }else{
		            var test = result.errmsg;
	            	for(i=0;i<test.length;i++){
	        			list.append('<p class="cf"><span class="r1">'+test[i]['num']+'</span><span class="r2">'+test[i]['name']+'</span><span class="r3">'+test[i]['score']+'</span</p>');
	        		}
	        		$("#rank .youRank .sort").html(result.cur_sort);
	        		$(".box").hide();
	        		$("#rank").show();
	                return false;
	            }
	            
	        }
	    });
		
		
	});
	
	$(".myBtn").click(function(){
		var i;
		var list = $("#my .myList");
		list.empty();
		$.ajax({
	        async:false,
	        url:'../../phone/rpgame/worth',
	        type: "post",
	        dataType:'json',
	        success:function(result){
	            //数据返回后执行
	            if(result.errcode != 0){
	                alert(result.errmsg);
	                return false;
	            }else{
		            var test1 = result.errmsg;
	            	for(i=0;i<test1.length;i++){
	        			list.append('<p class="cf">'+
	        							'<span class="r1">'+test1[i]['add_time']+'</span>'+
	        							'<span class="r2">通过游戏获得'+test1[i]['score']+'积分</span>'+
	        						'</p>');
	        		}
	        		
	        		$(".box").hide();
	        		$("#my").show();
	                return false;
	            }
	            
	        }
	    });
		
	});
	$(".indexBtn").click(function(){
		$(".box").hide();
		$("#index").show();
	});
	$(".reload").click(function(){
		location.reload();
	});

})

	var mebtnopenurl = '';
	var myData = { gameid: "shuqian" };
	var changeTitle = "";		
	function goHome(){}
	function clickMore(){}
	function dp_share(){}
	function dp_Ranking(){}
	function onShareComplete() {}
    function getSuffixes() {}
    function playDudulu(){
	    var oAudio = document.getElementById('playDudulu');
	    oAudio.play();
	}
</script>
<link rel="stylesheet" type="text/css"  href="/rpgame/css/com.css" />
</head>
<body>
	<div class="warp">
		<div id="game" class="box game hide">
			<canvas id="stage" width="640" height="960">
			您的浏览器不支持html5, 请换用支持html5的浏览器。
			</canvas>
			<p class="_time" id="_time">8</p>
			<p class="_score" id="_score">0</p>
		</div>
		<!-- 首页 -->
		<div class="index box " id="index">
			<img src="/rpgame/images/title.png" class="title" />
			<div class="rule">
				<img src="/rpgame/images/ruleBg.png" class="ruleBg" />
				<div class="ruleText">
					<p>●  8秒内能扯下多少红包送多少积分！</p>
					<p>●  红包内积分随机</p>
					<p>●  只能通过验证已激活的卡号ID获取游戏机会</p>
					<p>●  每个卡号ID只能验证使用一次</p>
				</div>
			</div>
			<div class="form">
				<input type="text" placeholder="请输入卡号ID" id="cardID" />
				<img src="/rpgame/images/startBtn.png" class="startBtn" id="startBtn" />
			</div>
			<div class="btnBox">
				<img src="/rpgame/images/rankBtn.png" class="bottomBtn rankBtn"  />
				<img src="/rpgame/images/myBtn.png" class="bottomBtn myBtn" />
			</div>
		</div>
		<!-- 倒计时 -->
		<div class="djs box hide" id="djs">
			<div class="djsWarp">
				<img src="/rpgame/images/djs3.png" class="djs3" />
				<img src="/rpgame/images/djs2.png" class="djs2 hide" />
				<img src="/rpgame/images/djs1.png" class="djs1 hide" />
			</div>
		</div>
		<!-- 排行榜 -->
		<div class="rank box hide" id="rank">
			<div class="rankWarp">
				<img src="/rpgame/images/rankTitle.png" class="rankTitle" />
				<div class="rankList"></div>
			</div>
			<p class="youRank">您现在处于<span class="city">{{ agentCity }}</span>排行榜第<span class="sort">xxxx</span>名</p>
			<div class="btnBox">
				<img src="/rpgame/images/myBtn.png" class="bottomBtn myBtn" />
				<img src="/rpgame/images/indexBtn.png" class="bottomBtn indexBtn" />
			</div>
		</div>
		<!-- 我的资产 -->
		<div class="my box hide" id="my">
			<p class="name">{{ agentName }}</p>
			<p class="score">目前积分：{{ agentScore }}</p>
			<div class="myWarp">
				<img src="/rpgame/images/myTitle.png" class="myTitle" />
				<div class="myList"></div>
				<p class="myTips">具体积分奖励详情请咨询线下门店负责人</p>
				<div class="btnBox">
					<img src="/rpgame/images/rankBtn.png" class="bottomBtn rankBtn" />
					<img src="/rpgame/images/indexBtn.png" class="bottomBtn indexBtn" />
				</div>
			</div>
		</div>
		<!-- 结果 -->
		<div class="result hide" id="result">
			<div class="resultWarp">
				<span class="close reload">×</span>
				<p class="title " >本次游戏获得积分为:<span class="result_score">0</span></p>
				<p class="" >目前总积分为：<span class="result_all_score">0</span></p>
				<img src="/rpgame/images/indexBtn2.png" class="indexBtn2 reload" />
			</div>
		</div>
		<!-- 首次登陆 -->
		{% if agentTag %}
		<div class="frist hide" id="frist">
		{% else %}
		<div class="frist" id="frist">
		{% endif %}
			<div class="fristWarp">
				<p>首次登入必填</p>
				<p>
					<select class="city" id="city">
						<option>您所在的城市</option>
						<option>贵阳</option>
						<option>哈尔滨</option>
						<option>杭州</option>
						<option>济南</option>
						<option>昆明</option>
						<option>南昌</option>
						<option>南京</option>
						<option>青岛</option>
						<option>厦门</option>
						<option>石家庄</option>
						<option>太原</option>
						<option>天津</option>
						<option>武汉</option>
						<option>西安</option>
						<option>长沙</option>
						<option>郑州</option>
						<option>北京</option>
						<option>东莞</option>
					</select>
				</p>
				<p><input type="text" class="name" placeholder="您的姓名" id="name" /></p>
				<div  >
					<!-- <img src="/rpgame/images/loginBtn.png" class="loginBtn" /> -->
					<input type="button" value="点我"  id="submitinfo" >
					
				</div>
			</div>
		</div>
	</div>
<audio id="playDudulu" hidden="true" style="display:none;">
	<source src="/rpgame/audio/dudulu.OGG" type="audio/ogg">
	<source src="/rpgame/audio/dudulu.mp3" type="audio/mpeg">
	Your browser does not support the audio element.
</audio>



</body>
</html>