<div class="m-b-sm">
<div class="btn-group" ng-init="radioModel = 'Male'">
  <a href="/admin/qmjjg/index"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>报名数据表</label></a>
  <a href="/admin/qmjjg/baoming_statistics"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>报名数据统计</label></a>
  <!-- <a href="/admin/qmjjg/budian"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>布点数据表</label></a> -->
  <a href="/admin/qmjjg/budian_statistics"><label class="btn btn-default btn-sm"><i class="fa fa-check text-active"></i>布点数据统计</label></a>
</div>
</div>