
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope"><h1 class="m-n font-thin h3">活动数据</h1></div>
			
			<div class="wrapper-md ng-scope form-inline" style="padding:10px 20px 0px 20px;">
				<a class="btn btn-default btn-sm" href="/admin/vcard/index" role="button" style="margin-right:10px;">返回</a>
			</div>			
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<div class="table-responsive">
						<table class="table table-hover table-condensed m-b-none">
							<thead>
								<tr>
									<th>ID</th>
									<th>活动名称</th>
									<th>报名人数</th>
									<th>v卡激活数</th>
									<th>领券数</th>
									<th>新用户数</th>
									<th>操作</th>
								</tr>
							</thead>
							<tbody>
						{% for k in data %}
								<tr class="odd">
									<td>{{ k['id'] }}</td>
									<td>{{ k['name'] }}</td>
									<td>{{ k['register_count'] }}</td>
									<td>{{ k['vcard_count'] }}</td>
									<td>{{ k['vcard_active'] }}</td>
									<td>{{ k['new_count'] }}</td>
									<td>
										<a href="/admin/vcard/userinfo/{{ k['id'] }}">用户信息</a>
										
									</td>
								</tr>
						{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<?php $this->partial("index/footer")?>

<script type="text/javascript">

function delaction(m){
	var r=confirm("你确定要删除该活动吗？");
	if(r == true){
		location.href="/admin/vcard/index/delete/"+m;
	}
}

</script>