
<?php $this->partial("index/head")?>
<?php $this->partial("index/menu")?>

<div class="app-content ng-scope" style="font-size:12px;">
	<div class="app-content-body fade-in-up ng-scope" ui-view="">
		<div ui-view="" class="ng-scope">
			<div class="bg-light lter b-b wrapper-md ng-scope"><h1 class="m-n font-thin h3">用户信息</h1></div>
			
			<div class="wrapper-md ng-scope form-inline" style="padding:10px 20px 0px 20px;">
				<a class="btn btn-default btn-sm" href="/admin/vcard/statcity/{{ actionid }}" role="button" style="margin-right:50px;">返回</a>
				{% if regtag == 1%}<a class="btn btn-default btn-sm" href="/admin/vcard/userinfo/{{ actionid }}/0" role="button" style="margin-right:10px;">全部</a>
				{% else %}<a class="btn btn-default btn-sm" href="/admin/vcard/userinfo/{{ actionid }}/1" role="button" style="margin-right:10px;">已激活</a>
				{% endif %}
			</div>		
			
			<div class="wrapper-md ng-scope" style="padding:10px 20px 10px 20px;">
				<div class="panel panel-default">
					<div class="table-responsive">
						<table class="table table-hover table-condensed m-b-none">
							<thead>
								<tr>
									<th>ID</th>
									<th>手机号</th>
									<th>用户名</th>
									<th>激活状态</th>
									<th>激活时间</th>
									<th>是否新用户</th>
									<th>是否领券</th>
								</tr>
							</thead>
							<tbody>
						{% for k in list %}
								<tr class="odd">
									<td>{{ k['id'] }}</td>
									<td>{{ k['phone'] }}</td>
									<td>{{ k['user_name'] }}</td>
									<td>
									{% if k['is_active'] %}<span class="label bg-success">已激活</span>
                                    {% else %}<span class="label bg-danger">未激活</span>
                                    {% endif %}
                                    </td>
									<td>{{ k['active_time'] }}</td>
									<td>
									{% if k['is_new'] == 1 %}<span class="label bg-success">新用户</span>
                                    {% else %}
                                    {% endif %}
                                    </td>
									<td>
									{% if k['status'] == 1 %}<span class="label bg-success">已领券</span>
                                    {% else %}
                                    {% endif %}
									</td>
									
								</tr>
						{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="row">
					   
					</div>
					{% if page <> '' %}
                    <?php $this->partial("index/page")?>
                    {% endif %}
				</div>
			</div>
		</div>
	</div>
</div>


<?php $this->partial("index/footer")?>

<script type="text/javascript">

function delaction(m){
	var r=confirm("你确定要删除该分站吗？");
	if(r == true){
		location.href="/admin/group/delete/id/"+m;
	}
}

</script>