<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>全民家居购-V卡激活</title>
<meta name="keywords" content="优居网 优品团" />
<meta name="description" content="优居网 优品团" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />

<style>
body {height:100%;  font: 12px/1.75  \5FAE\8F6F\96C5\9ED1;}
div, html, body, p, ul, ol, li, a, form, img, table, td, h1, h2, h3, h4, h5, h6, blockquote, header, section, footer, aside, nav, article, figure, figcaption, dl, dt, dd {margin:0;padding:0;} 

.cf:before,.cf:after{content:"";display:table;}.cf:after{clear:both;}.cf{zoom:1;}
body,a,a:link{color:#666;}
a,a:link{text-decoration:none;}
a:hover{text-decoration:none;}

.succeed{width: 100%;color: #fff;position: absolute;top:0;left: 0;z-index: 2;background: url(/qmjjg/images/succeedBg.jpg) no-repeat #fdd207 top;background-size: 100%}
.succeed img{width: 100%}
.succeed .logo2{width: 100%}
.succeed .text{font-size: 16px;color: #630000;text-align: center;}
.succeed .text span{padding-left: 25px;background: url(/qmjjg/images/icon.png) no-repeat top left;background-size: 20px}
.succeed .hb{width: 80%;margin:5px 10% 0 10%;position: relative;}
.succeed .hb p{width: 100%;text-align: center;position: absolute;top: 0;left: 0;color: #ffd71b;font-size: 30px;margin-top: 20%}

.succeed .ad{display: block;margin:5px 10px 0 10px;}
.succeed .ad .adTitle{position: relative;color: #630000;text-align: center;}
.succeed .ad .adTitle .line{width: 100%;height: 3px;border-top: 3px solid #630000;border-bottom: 1px solid #630000;position: absolute;top: 12px;left: 0}
.succeed .ad .adTitle span{padding:0 10px;font-size: 16px;background: #fdd207;position: relative;z-index: 1}
.succeed .ad1 .adMain{background: #fff;padding:5px;  font-size: 0;}
.succeed .ad1 .adMain p{text-align: center;background: #ff6325;color: #fff}
.copyright{color: #8a5b01;text-align: center;}

</style>

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>
	<div class="wraper">
		
		<div class="succeed hide" id="succeed">
			<div class="logo2">
			<img src="/qmjjg/images/logo.png"   />
		</div>
		<p class="text"><span>{% if endtag == 0 %}恭喜您，获得抵扣券一个{% else %}此活动已结束！你还可以参加以下活动{% endif %}</span></p>
		<div class="hb">
			<img src="/qmjjg/images/hb.png" />
			<p>100元</p>
		</div>
		<p><img src="/qmjjg/images/succeedTips.png"  /></p>
			<a class="ad ad1" href="/phone/yiyuanqiang/index/6" id="jihuo01" >
				<div class="adTitle">
					<p class="line"></p>
					<span>家居建材全民砍价</span>
				</div>
				<div class="adMain">
					<img src="/qmjjg/images/succeed1.jpg" />
					<p>关注优居公众号参与全民砍价</p>
				</div>
			</a>
			<a class="ad ad2" href="/phone/group/index?from=jh" id="jihuo02" >
				<div class="adTitle">
					<p class="line"></p>
					<span>优品团到店特卖</span>
				</div>
				<img src="/qmjjg/images/succeed2.png" />
			</a>
			<p class="copyright">Copyright 2015  版权归深圳亚太传媒科技开发有公司所有</p>
		</div>
		
	</div>

<script src="/common/js/zepto.min.js"></script>
<script>


	$(function(){
		$("#loading").hide();
		setTimeout(function(){
			var h = $(window).height();
			if($("#succeed").height()<h){
	            $("#succeed").height("100%")
	        }
		},500);
		
		
		
	});
</script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">
var wxData = {
		imgUrl:"{{domain}}/vcard/images/fx.jpg",
		link:"{{domain}}/phone/qmjjg/index.html",
		desc:"送100元抵扣券-快抢全民家居购免费门票，领票就送100元抵购券。",
		title:"送100元抵扣券-快抢全民家居购免费门票，领票就送100元抵购券。",
		
	};
	
wx.config({
      debug: false,
      appId: "{{ signPackage['appId'] }}",
	  timestamp: "{{ signPackage['timestamp'] }}",
	  nonceStr: "{{ signPackage['nonceStr'] }}",
      signature: "{{ signPackage['signature'] }}",
      jsApiList: [
        'checkJsApi',
        'onMenuShareTimeline',
        'onMenuShareAppMessage',
        'onMenuShareQQ',
        'onMenuShareWeibo'
      ]
});

wx.ready(function () {
	wx.onMenuShareAppMessage(wxData);
	wx.onMenuShareTimeline(wxData);
	wx.onMenuShareQQ(wxData);
});

</script>
</body>
</html>