<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>V卡激活</title>
<meta name="keywords" content="优居网 优品团" />
<meta name="description" content="优居网 优品团" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link rel="stylesheet" type="text/css"  href="/vcard/css/com.css" />

</head>
<body>
	<div class="cn-spinner loading" id="loading">
        <div class="spinner">

            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>
	<div class="wraper">
		
		<!-- 主要内容 -->
		<div class="main ">
			<!-- vCard激活成功 -->
			<div class="vCard vCardShare vCard2">
				<img src="/vcard/images/logo.png" class="logo" />
				<div class="hb">5元</div>
				<p class="p2">恭喜您成功获得优居抵扣券一个 </p>
				<p class="p2">我们已经将抵扣券放入优居优品公众号，请及时领取！</p>
				<!-- <p class="p2">您已经成功领取过抵扣券了哦！</p> -->
				
				<p class="ad" id="ad1"><img src="/vcard/images/ad.png" /></p>
				<p class="ad" id="ad2"><img src="/vcard/images/ad.png" /></p>
				<p class="copyright">Copyright 2015  版权归深圳前海优品优居网络科技有限公司所有</p>
			</div>

	
		</div>
		
	</div>

<script src="/common/js/zepto.min.js"></script>
<script>


	$(function(){
		$("#loading").hide();
		
		
		
	});
</script>

</body>
</html>