<?php $this->partial("yoju_public/head_exposition3")?>
<link type="text/css" rel="stylesheet" href="/exposition3/pc/css/com.css" media="all" />
<link type="text/css" rel="stylesheet" href="/exposition3/pc/css/style1.css" media="all" />
<script type="text/javascript">
var payDomain = '{{payDomain}}';
</script>
<div class="warp">

	<!-- 焦点图 -->
	<!-- 第三届优居家博会 -->
	<div class="expositionBox0 expositionBox" id="box0">
		<div class="insideBox">
			<img src="/exposition3/pc/images/light1.png" class="light light1" />
			<img src="/exposition3/pc/images/light2.png" class="light light2" />
		</div>
	</div>
	<!-- 报名 -->
	<!-- 第三届优居家博会 -->
	<div class="expositionBox1 expositionBox " id="box1">

		<div class="insideBox">
			<!-- 报名 -->
			<div class="process1 baoming1" id="baoming1" step="1">
				<div class="bmForm">
					<div class="step1">
						<p class="bmTitle">免费报名</p>
						<div class="inputBox nameBox">
							<p class="tips" tips="怎么称呼您">怎么称呼您</p>
							<input type="text" name="name" class="name"/>
						</div>
						<div class="inputBox telBox">
							<p class="tips" tips="请填写手机号码">请填写手机号码</p>
							<input type="text" name="tel" class="tel" />
						</div>
						<p class="tips2">*手机号仅用于本次报名</p>
						<p class="bmBtn">0元领票</p>
					</div>
					<div class="step2 hide">
						<p class="bmTitle">确认信息</p>
						<div class="inputBox codeBox">
							<p class="tips" tips="请填写短信验证码">请填写短信验证码</p>
							<input type="text" name="code" class="code"/>
						</div>
						<div class="inputBox quBox">
							<select class="area"></select>
						</div>
						<div class="inputBox addressBox">
							<p class="tips" tips="请填写详细地址">请填写详细地址</p>
							<input type="text" name="address" class="address" />
						</div>
						<p class="bmBtn">确认</p>
					</div>
					<div class="step3 hide">
						<p class="bmTitle">恭喜报名成功！</p>
						<img src="/exposition3/pc/images/ewm.png" class="ewm" />
						<p>扫描二维码获得更多优惠资讯!</p>
					</div>
				</div> 
			</div>
			<!-- 已报名轮播 -->
			<div class="bmInfo">
				<p class="num">
					<span>{{ count }}</span>人已成功报名
				</p>
				<p class="time" id="djs">
					<span class="text">剩余时间：</span>
					<span class="days bg">--</span>天
					<span class="hours bg">--</span>时
					<span class="minutes bg">--</span>分
					<span class="seconds bg">--</span>秒
				</p>
				<div id="marquee" class="marquee">
					<ul>
					{% for k,key in list %}
						<li class="cf"><span class="name">{{ key['name'] }}</span><span>{{ key['phone'] }}</span>已成功报名</li>
				    {% endfor %}
				        <li class="cf"><span class="name">陈**</span><span>1365****745</span>已成功报名</li>
						<li class="cf"><span class="name">程**</span><span>1362****524</span>已成功报名</li>
						<li class="cf"><span class="name">张**</span><span>1587****865</span>已成功报名</li>
						<li class="cf"><span class="name">何**</span><span>1360****125</span>已成功报名</li>
						<li class="cf"><span class="name">邓**</span><span>1591****185</span>已成功报名</li>
						<li class="cf"><span class="name">李**</span><span>1366****751</span>已成功报名</li>
						<li class="cf"><span class="name">彭**</span><span>1362****660</span>已成功报名</li>
						<li class="cf"><span class="name">陈**</span><span>1582****542</span>已成功报名</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<!-- 活动亮点 -->
	<!-- 第三届优居家博会 -->
	<div class="expositionBox2 expositionBox ex2Style1" id="box2">

		<div class="insideBox">
			<div class="title">活动亮点</div>
			<div class="boxMain gotoBM">
			</div>
		</div>
	</div>

	<!-- 参展大牌 -->
	<div class="expositionBox3 expositionBox" id="box3">
		<div class="insideBox">
			<div class="title">参展大牌</div>
			<div class="boxMain">
				<img src="/exposition3/pc/images/box3_1.jpg" class="box3_left" />
				<!--logo图片轮播-->
				<div id="logoSwiper" class="swiper logoSwiper">
					<div class="swiper-container">
						<div class="swiper-wrapper">
							<div class="swiper-slide">
								<img src="/exposition3/pc/images/logo/1.jpg" />
								<img src="/exposition3/pc/images/logo/2.jpg" />
								<img src="/exposition3/pc/images/logo/3.jpg" />
								<img src="/exposition3/pc/images/logo/4.jpg" />
								<img src="/exposition3/pc/images/logo/5.jpg" />
								<img src="/exposition3/pc/images/logo/6.jpg" />
								<img src="/exposition3/pc/images/logo/7.jpg" />
								<img src="/exposition3/pc/images/logo/8.jpg" />
								<img src="/exposition3/pc/images/logo/9.jpg" />
								<img src="/exposition3/pc/images/logo/10.jpg" />
								<img src="/exposition3/pc/images/logo/11.jpg" />
								<img src="/exposition3/pc/images/logo/12.jpg" />
								<img src="/exposition3/pc/images/logo/13.jpg" />
								<img src="/exposition3/pc/images/logo/14.jpg" />
								<img src="/exposition3/pc/images/logo/15.jpg" />
								<img src="/exposition3/pc/images/logo/16.jpg" />
								<img src="/exposition3/pc/images/logo/17.jpg" />
								<img src="/exposition3/pc/images/logo/18.jpg" />
								<img src="/exposition3/pc/images/logo/19.jpg" />
								<img src="/exposition3/pc/images/logo/20.jpg" />
							</div>
							<div class="swiper-slide">
								<img src="/exposition3/pc/images/logo/21.jpg" />
								<img src="/exposition3/pc/images/logo/22.jpg" />
								<img src="/exposition3/pc/images/logo/23.jpg" />
								<img src="/exposition3/pc/images/logo/24.jpg" />
								<img src="/exposition3/pc/images/logo/25.jpg" />
								<img src="/exposition3/pc/images/logo/26.jpg" />
								<img src="/exposition3/pc/images/logo/27.jpg" />
								<img src="/exposition3/pc/images/logo/28.jpg" />
								<img src="/exposition3/pc/images/logo/29.jpg" />
								<img src="/exposition3/pc/images/logo/30.jpg" />
								<img src="/exposition3/pc/images/logo/31.jpg" />
								<img src="/exposition3/pc/images/logo/32.jpg" />
								<img src="/exposition3/pc/images/logo/33.jpg" />
								<img src="/exposition3/pc/images/logo/34.jpg" />
								<img src="/exposition3/pc/images/logo/35.jpg" />
								<img src="/exposition3/pc/images/logo/36.jpg" />
								<img src="/exposition3/pc/images/logo/37.jpg" />
								<img src="/exposition3/pc/images/logo/38.jpg" />
								<img src="/exposition3/pc/images/logo/39.jpg" />
								<img src="/exposition3/pc/images/logo/40.jpg" />
							</div>
							<div class="swiper-slide">
								<img src="/exposition3/pc/images/logo/41.jpg" />
								<img src="/exposition3/pc/images/logo/42.jpg" />
								<img src="/exposition3/pc/images/logo/43.jpg" />
								<img src="/exposition3/pc/images/logo/44.jpg" />
								<img src="/exposition3/pc/images/logo/45.jpg" />
								<img src="/exposition3/pc/images/logo/46.jpg" />
								<img src="/exposition3/pc/images/logo/47.jpg" />
								<img src="/exposition3/pc/images/logo/48.jpg" />
								<img src="/exposition3/pc/images/logo/49.jpg" />
								<img src="/exposition3/pc/images/logo/50.jpg" />
								<img src="/exposition3/pc/images/logo/51.jpg" />
								<img src="/exposition3/pc/images/logo/52.jpg" />
								<img src="/exposition3/pc/images/logo/53.jpg" />
								<img src="/exposition3/pc/images/logo/54.jpg" />
								<img src="/exposition3/pc/images/logo/55.jpg" />
								<img src="/exposition3/pc/images/logo/56.jpg" />
								<img src="/exposition3/pc/images/logo/57.jpg" />
								<img src="/exposition3/pc/images/logo/58.jpg" />
								<img src="/exposition3/pc/images/logo/59.jpg" />
								<img src="/exposition3/pc/images/logo/60.jpg" />
							</div>
							<div class="swiper-slide">
								<img src="/exposition3/pc/images/logo/61.jpg" />
								<img src="/exposition3/pc/images/logo/62.jpg" />
								<img src="/exposition3/pc/images/logo/63.jpg" />
								<img src="/exposition3/pc/images/logo/64.jpg" />
								<img src="/exposition3/pc/images/logo/65.jpg" />
								<img src="/exposition3/pc/images/logo/66.jpg" />
								<img src="/exposition3/pc/images/logo/67.jpg" />
							</div>
						
							
						</div>
					</div>	
					<div class="paginationWarp">
						<span class="pagination"></span>
					</div>
					<span class="arrow arrow-left"></span>
					<span class="arrow arrow-right"></span>
				</div>
			</div>
		</div>
	</div>

	<!-- 产品优惠 -->
	<div class="expositionBox4 expositionBox" id="box4">
		<div class="insideBox">
			<div class="title">产品优惠</div>
			<div class="boxMain" id="product">
			    <div class="productNav">
			    	<span class="hover">★<i>一元抢购</i></span>
			    	<span>★<i>产品预定</i></span>
			    </div>
			    <div class="productMain">
			    	<div class="productBox">
			    		<!--现场抢购轮播-->
						<div id="qiangSwiper" class="swiper qiangSwiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
								{% for x,y in goods_arr2 %}
									<div class="swiper-slide">
                                        {% for k,key in y %}
										<div class="product" describe="{{ key['goods_info'] }}" ewmImg="{{ key['code_img'] }}">
											<img src="{{ key['goods_img'] }}" class="proImg"/>
											<div class="proInfo">
												<div class="proInfoLeft">
													<p class="proTitle">{{ key['goods_name'] }}</p>
													<p class="original">原价：￥{{ key['market_price'] }}</p>
													<p>限<span class="red">{{ key['stock'] }}</span>套，每人限1套</p>
												</div>
												<div class="proInfoRight">
													<p>抢购价</p>
													<p class="price">{{ key['order_price'] }}</p>
													<i> </i>
												</div>
											</div>
										</div>
                                        {% endfor %}
									</div>
								{% endfor %}
								</div>
							</div>	
							<div class="paginationWarp">
								<span class="pagination"></span>
							</div>
						</div>
			    	</div>
			    	<div class="productBox">
			    		<!--产品预定轮播-->
						<div id="dingSwiper" class="swiper dingSwiper">
							<div class="swiper-container">
								<div class="swiper-wrapper">
								{% for x,y in goods_arr1 %}
									<div class="swiper-slide">
									{% for k,key in y %}
										<div class="product" describe="{{ key['goods_info'] }}">
											<img src="{{ key['goods_img'] }}" class="proImg" />
											<div class="proInfo">
												<div class="proInfoLeft">
												<input type="hidden" value="{{ key['id'] }}" class="goods_id">
													<p class="proTitle">{{ key['goods_name'] }}</p>
													<p class="original">原价：￥{{ key['market_price'] }}</p>
													<p>限<span class="red">{{ key['stock'] }}</span>套，每人限1套</p>
												</div>
												<div class="proInfoRight">
													<p>免费预定</p>
													<p class="price">{{ key['order_price'] }}</p>
													<i> </i>
												</div>
											</div>
										</div>
									{% endfor %}
									</div>
								{% endfor %}
								</div>
							</div>	
							<div class="paginationWarp">
								<span class="pagination"></span>
							</div>
						</div>
			    	</div>
			    </div>
			</div>
		</div>
	</div>

	<!-- 贴心服务 -->
	<!-- 第三届优居家博会 -->
	<div class="expositionBox5 expositionBox " id="box5">

		<div class="insideBox">
			<div class="title">贴心服务</div>
			<div class="boxMain">
			</div>
		</div>
	</div>

	
	<!-- 展会地址 -->
	<div class="expositionBox6 expositionBox" id="box6">
		<div class="insideBox">
			<div class="title">展会地址</div>
			<div class="boxMain adressBox cf">
				<div class="map" id="map"></div>
				<div class="info">
					<div class="adInfo time">
						<span>活动时间</span>
						<p>2016.2.26-2.28</p>
					</div>
					<div class="adInfo adress">
						<span>活动地址</span>
						<p>上海漕宝路88号光大会展中心</p>
					</div>
					<div class="adInfo metro">
						<span>地铁线路</span>
						<p>地铁:地铁1号线，至漕宝路1号口出，往西方向步行500米</p>
					</div>
					<div class="adInfo bus">
						<span>公交线路</span>
						<p>(1)乘坐120路、166路、43路、809路、92路B线、92路、946路上乘线、沪松线专线、沪松线、找到漕宝路习勤路下车即到；</p>
						<p>(2)乘坐166路、43路、92路B线、92路到漕河（漕宝路漕溪路）下车步行220米；</p>
						<p>(3)乘坐809路、946路上乘线、沪松专线、沪松线、沪陈线到漕河泾（漕宝路闵路）下车步行300米；</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<!-- 右侧导航 -->
	<!-- 第三届优居家博会 -->
	<div class="expositionnav expositionnavStyle1 hide" id="expositionnav">

		<div class="expositionlist">
			<p class="nav1"><span>0元领票</span></p>
			<p class="nav2"><span>活动亮点</span></p>
			<p class="nav3"><span>参展大牌</span></p>
			<p class="nav4"><span>产品优惠</span></p>
			<p class="nav5"><span>买后无忧</span></p>
			<p class="nav6"><span>展会地址</span></p>
			<p class="gototop"></p>
		</div>
	</div>

	<!-- 底部跟随报名条 -->
	<div class="process1 baoming3 hide" id="baoming3">
		<div class="insideBox">
			<!-- 第三届优居家博会 -->
			<img src="/exposition3/pc/images/bottom.png" class="bm2"  />

			<!-- <div class="bmForm">
				<div class="inputBox nameBox">
					<p class="tips" tips="怎么称呼您">怎么称呼您</p>
					<input type="text" name="name" class="name" placeholder="" />
				</div>
				<div class="inputBox telBox">
					<p class="tips" tips="请填写手机号码">请填写手机号码</p>
					<input type="text" name="tel" class="tel" placeholder="" />
				</div>
				<div class="inputBox getCodeBox">
					<p class="getCode">获取验证码</p>
				</div>
				<div class="inputBox codeBox">
					<p class="tips" tips="请填写短信验证码">请填写短信验证码</p>
					<input type="text" name="code" class="code " placeholder="" />
				</div>
				<div class="inputBox areaBox">
					<select class="area"></select>
				</div>
				<div class="inputBox addressBox">
					<p class="tips" tips="请填写详细地址">请填写详细地址</p>
					<input type="text" name="address" class="address" />
				</div>
				<div class="bmBtn">
					<p>0元领票</p>
				</div>
			</div> -->
			<div class="bmForm">
				<div class="step1 cf">
					<div class="inputBox nameBox">
						<p class="tips" tips="怎么称呼您">怎么称呼您</p>
						<input type="text" name="name" class="name"/>
					</div>
					<div class="inputBox telBox">
						<p class="tips" tips="请填写手机号码">请填写手机号码</p>
						<input type="text" name="tel" class="tel" />
					</div>
					<p class="bmBtn">0元领票</p>
				</div>
				<div class="step2 cf hide">
					<div class="inputBox codeBox">
						<p class="tips" tips="请填写短信验证码">请填写短信验证码</p>
						<input type="text" name="code" class="code"/>
					</div>
					<div class="inputBox areaBox">
						<select class="area"></select>
					</div>
					<div class="inputBox addressBox">
						<p class="tips" tips="请填写详细地址">请填写详细地址</p>
						<input type="text" name="address" class="address" />
					</div>
					<p class="bmBtn">确认</p>
				</div>
			</div> 
		</div>
	</div>

	<!-- 通用黑色背景 -->
	<div class="blackBg hide" id="blackBg"></div>
	<!-- 弹出报名 -->
	<div class="tcBm tc hide" id="tcBm">
		<span class="close">×</span>
		<!-- 产品介绍 -->
		<div class="tcProduct">
			<div class="productL">
				<img src="" class="productImg" />
				<div class="info">
					<p class="original">原价：￥12000</p>
					<p class="limite">限<span class="red">20</span>套，每人限1套</p>
					<div class="priceBox">
						<p>抢购价</p>
						<p class="price">99999</p>
					</div>
				</div>
			</div>
			<div class="productR">
				<p class="title">产品标题</p>
				<p class="tips1">微信扫描二维码参与</p>
				<p class="describe">产品描述</p>
				<img src="" class="ewmImg" />
			</div>
		</div>
		<!-- 报名 -->
		<div class="process1 baoming2" id="baoming2" step="1" >
			<div class="bmForm">
				<div class="step1">
					<p class="bmTitle">免费报名</p>
					<div class="inputBox nameBox">
						<p class="tips" tips="怎么称呼您">怎么称呼您</p>
						<input type="text" name="name" class="name"/>
					</div>
					<div class="inputBox telBox">
						<p class="tips" tips="请填写手机号码">请填写手机号码</p>
						<input type="text" name="tel" class="tel" />
					</div>
					<p class="tips2">* 手机号仅用于本次报名</p>
					<p class="bmBtn">0元领票</p>
				</div>
				<div class="step2 hide">
					<p class="bmTitle">确认信息</p>
					<div class="inputBox codeBox">
						<p class="tips" tips="请填写短信验证码">请填写短信验证码</p>
						<input type="text" name="code" class="code"/>
					</div>
					<div class="inputBox areaBox">
						<select class="area"></select>
					</div>
					<div class="inputBox addressBox">
						<p class="tips" tips="请填写详细地址">请填写详细地址</p>
						<input type="text" name="address" class="address" />
					</div>
					<p class="tips2">* 您的个人地址用于快递门票，绝对保密，请放心填写</p>
					<p class="bmBtn">确认</p>
				</div>
				<div class="step3 hide">
					<p class="bmTitle">恭喜报名成功！</p>
					<img src="/exposition3/pc/images/ewm.png" class="ewm" />
					<p>扫描二维码</p>
					<p>获得更多优惠资讯!</p>
				</div>
			</div> 
		</div>
	</div>
	<!-- 弹出预约 -->
	<div class="tcBm tc hide" id="tcYy">
		<span class="close">×</span>
		<!-- 产品介绍 -->
		<div class="tcProduct">
			<div class="productL">
				<img src="" class="productImg" />
				<div class="info">
				<input type="hidden" value="" class="goods_id">
					<p class="original">原价：￥</p>
					<p class="limite">限<span class="red"></span>套，每人限1套</p>
					<div class="priceBox">
						<p>免费预定</p>
						<p class="price">99999</p>
					</div>
				</div>
			</div>
			<div class="productR">
				<p class="title">产品标题</p>
				<p class="tips2">线上预定，现场购买！</p>
				<p class="tips1">数量有限，先到先得</p>
				<p class="describe">产品描述</p>
			</div>
		</div>
		<!-- 预约 -->
		<div class="baoming2" id="yuyue" step="1" >
			<div class="bmForm">
				<div class="step1">
					<p class="bmTitle">免费预定</p>
					<div class="inputBox nameBox">
						<p class="tips" tips="怎么称呼您">怎么称呼您</p>
						<input type="text" name="name" class="name"/>
					</div>
					<div class="inputBox telBox">
						<p class="tips" tips="请填写手机号码">请填写手机号码</p>
						<input type="text" name="tel" class="tel" />
					</div>
					<p class="tips2">* 手机号仅用于本次预定</p>
					<p class="bmBtn">申请预定</p>
				</div>
			
				<div class="step3 hide">
					<p class="bmTitle">恭喜预约成功！</p>
					<img src="/exposition3/pc/images/ewm.png" class="ewm" />
					<p>扫描二维码</p>
					<p>获得更多优惠资讯!</p>
				</div>
			</div> 
		</div>
	</div>
	<!-- 弹出成功 -->
	<div class="succeedTc tc hide" id="succeedTc">
		<span class="close">×</span>
		<p class="succeedTitle">恭喜报名成功！</p>
	</div>


</div>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=55TvHWH5h9OAPPLtfdqFFBRB"></script>
<script type="text/javascript" src="/common/js/idangerous.swiper-2.1.min.js"></script>
<script type="text/javascript" src="/exposition3/pc/js/jquery.kxbdmarquee.js"></script>
<script type="text/javascript" src="/exposition3/pc/js/com.js"></script>

<?php $this->partial("yoju_public/footer")?>