{% if page['linkPage'] != '' %}
<div class="row">
<div class="col-xs-page">
    <div class="dataTables_paginate paging_simple_numbers">
    <ul class="pagination pagination-sm">
    {% if page['theFirst'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['theFirst']?>">第一页</a></li>
    {% endif %}
    {% if page['upPage'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['upPage']?>"><i class="fa fa-chevron-left"></i></a></li>
    {% endif %}
    {% if page['prePage']['rollPage'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['prePage']['url']?>"><?php echo $page['prePage']['rollPage']?></a></li>
    {% endif %}
    {% if page['linkPage'] != '' %}
    {% for k,key in page['linkPage'] %}
        <li class="paginate_button {% if key == ''%}active{% endif %}"><a href="{{ key }}">{{ k }}</a></li>
    {% endfor %}
    {% endif %}
        <li class="paginate_button next" id="DataTables_Table_0_next"></li>
    {% if page['nextPage']['rollPage'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['nextPage']['url']?>"><?php echo $page['nextPage']['rollPage']?></a></li>
    {% endif %}
    {% if page['downPage'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['downPage']?>"><i class="fa fa-chevron-right"></i></a></li>
    {% endif %}
    {% if page['theEnd'] != '' %}
        <li class="paginate_button previous"><a href="<?php echo $page['theEnd']?>">最后一页</a></li>
    {% endif %}
     </ul>
     </div>
 </div>
</div>
{% endif %}